.eslintrc.js
package-lock.json
package.json
src/App.tsx
src/index.tsx
src/pages/admin/SeminarManage.tsx
src/pages/home/Home.tsx
src/router/useMainRouter.tsx

> - #109
> 각 경로로 접근 시 해당 페이지 컴포넌트 불러올 수 있도록 라우터 설정
> .
>
- 리뷰 예상 시간 : `5분`
- `useMainRouter.tsx`에 라우트 설정한 부분 집중적으로 봐주시면 될 것 같습니다.

Feature/라우터 설정하기 #109

---

package-lock.json
package.json
postcss.config.js
src/index.tsx
src/tailwind.css
tailwind.config.js

- close #158
- tailwindcss 설치 및 초기 설정
- material tailwind 설치 및 초기 설정
- tailwindcss, material tailwind 설치하고 사용 가능하도록 초기 구성 해두고, 정상적으로 동작하는 것 확인하였습니다.
> 5분

Feature/tailwind 관련 설정 #158

---

.eslintrc.js
package-lock.json
package.json
prettier.config.js

- close #162
tailwindcss의 순서를 자동으로 정렬해주는 플러그인을 추가하였습니다.
prettier-plugin-tailwindcss 플러그인 설치 및 설정파일 작성
플러그인만 추가해서 별도로 리뷰를 할 필요는 없을 것 같습니다!

Feature/tailwindcss plugin 추가 #162

---

package-lock.json
package.json
src/index.tsx

- Close #175 
- recoil 사용 환경 구성
- recoil 설치
- recoil 사용 시 필요한 `RecoilRoot` 씌워주기
- 1분, 주의깊게 봐야할 부분은 크게 없습니다!

Feature/recoil 설치 및 세팅 #175

---

.gitignore
package-lock.json
package.json
src/api/aboutApi.ts
src/api/dto.ts
src/index.tsx
tsconfig.paths.json

- Close #177 
- `react query`와 `axios`를 사용하여 API 호출 및 관리가 가능하도록 처리
- `react query`와 `axios` 설치 및 사용가능 하도록 세팅
- 구현 방식을 보여주고자 about API 부분 코드 작성
10분, 폴더 구조 및 변수명 타입 처리 방식 부분 중점적으로 봐주시면 좋을 것 같습니다!

Feature/api 받아오는 기본 틀 생성 #177

---

.eslintrc.js

- close #184
옵셔널 타입 사용 시 에러가 발생하는 규칙에 대해 off 설정을 해주었음.
react/require-default-props, react/no-unused-prop-types 설정을 off로 설정해주었습니다.
1분! 설정만 몇 개 추가해준 거라 별다른 리뷰 사항은 없을 겁니다!

Feature/EsLint_설정_수정 #184

---

tsconfig.paths.json

- Close #203
- API 임시 데이터 저장 폴더 `mocks` 절대 경로 추가
- 1분
- 딱히 주의 깊게 봐야할 부분은 없습니다!
- 해당 경로 잘 받아와지는 것 테스트 완료하였습니다!

Feature/mocks 절대경로 설정 #203

---

tailwind.config.js

- #168
폰트 단위 pt에서 px로 변경 
폰트 사이즈 12->10 변경

Feature/tailwind 커스텀 폰트 사이즈 단위 변경 #168

---

package-lock.json
package.json

- #233
- react icons 설치했씁니다! 잘뜨는거 확인했습니다
- 0.1분,

Feature/react icon 설치

---

src/components/Button/FilledButton.tsx
src/components/Button/OutlinedButton.tsx
src/components/Button/TextButton.tsx

- #200
- tailwincss 유틸리티 정렬 맞춰주었습니다.
- 0.5분, 유틸리티 순서만 변경된 거라 크게 봐야할 부분은 없습니다.

Feature/버튼 tailwincss 유틸리티 정렬 #200

---

package-lock.json
package.json

- Close #245
- 날짜/시간 관리 라이브러리 luxon Typescript에서도 사용가능하도록 @types/luxon 설치
- 0.2분

Feature/luxon 타입 정의된 라이브러리 설치 #245

---

src/components/Table/StandardTable.interface.ts
src/components/Table/StandardTable.tsx

- #130
- 컬럼별 데이터 셀 가공 가능하도록 기능 추가
- `childComponent` 함수에 column `key`를 받아와 해당 column의 cell들을 해당 함수에서 return되는 element로 변경할 수 있도록 처리
- 기존 값을 바탕으로 가공을 해야하기 때문에 `value`라는 prop으로 기존 값을 받아오도록 처리
- 데이터 가공 시 버튼을 클릭해 해당 row정보가 사용되는 모달을 띄워주는 등의 기능까지 확장하기 위해 `rowData`로 선택된 row 정보도 받아올 수 있도록 처리
- 10분
```tsx
import OutlinedButton from '@components/Button/OutlinedButton';
import StandardTable from '@components/Table/StandardTable';
import ChildComponent from '@components/Table/StandardTable.interface';
interface ExampleRow {
id: number;
no: number;
title: string;
writer: string;
createDate: string;
watching: number;
state: string;
}
interface ExampleColumn {
key: keyof ExampleRow;
headerName: string;
}
const columns: ExampleColumn[] = [
{
key: 'no', …
```

Feature/테이블 데이터 셀 가공 가능하도록 처리 #130

---

src/components/Layout/Header/Header.tsx
src/components/Layout/Header/Menu/AccountMenu.tsx

- Close #103
- 추후 작업 #269, #270
- 헤더에 각 로고 및 아이콘 배치하고 클릭시 기능들 추가해주었습니다.
- 5분

Feature/헤더 구성 #103

---

src/components/Layout/Container/FullContainer.tsx

- Close #274
- FullContainer 하위에서도 넓이 전체로 잡을 수 있도록 full로 넓이 지정해주기
- 0.1분

Feature/FullContainer 넓이 full로 잡기

---

src/components/Table/StandardTable.tsx

- Close #280
- 테이블과 페이지네이션 사이 간격이 외부 요소에 영향 받지 않게 개선
- 0.1분

Feature/테이블과 페이지네이션 사이 간격 고정 #280

---

src/components/Modal/ActionModal.tsx

> - #263 
> - #190
> 공통 컨폼 모달을 만들면서 모달끼리의 정형화를 위해 공통 액션 모달에 수정이 필요한 디자인 요소들을 리팩토링했습니다.
> 공통 컴포넌트이지만 코드나 기능이 변화되는 것이 아니라서 `priority-low`로 적용했습니다.
> - 커스텀 컴포넌트 적용 (버튼, 색상, 글자 크기)
> - 모달창 크기
>   모달창 크기의 경우에는 컨폼 모달과 일치 시켰습니다.
> 3분
> 공통 컨폼 모달이랑 코드가 유사해서 리뷰가 간단할 걸로 예상합니다!

Feature/공통 액션 모달 디자인 리팩토링 #263

---

src/pages/senimarAttend/SenimarAttend.tsx

> fillButton import 안한채로 머지돼서 오류생기는 거 수정했습니다~!! 
바로 머지해주시면 됩니다.

fix: fillButton import 안한거 수정

---

src/components/Input/SearchInput.tsx

> - close #240
- props에 (state, stateHandler, 동작할 함수) 5개 넣어줘야함
- 검색아이콘 클릭 + 검색창에서 엔터시 함수 동작하도록
- className props로 넣어 tailwind css적용되도록
``` tsx
import SearchInput from '@components/Input/SearchInput';
const Home = () => {
const [inputText, setInputText] = React.useState<string>('');
const handleInputText = (e: React.ChangeEvent<HTMLInputElement>) => {
setInputText(e.target.value);
};
const handleSearchBook = () => {
console.log(inputText);
};
return (
<div>
<SearchInput
className="w-full "
label="도서 검색"
value={inputText}
onChange={handleInputText}
onSearchButtonClick={handleSearchBook}
/>
</div>
);
};
export default Home;
```
> 3분, tailwind 적용잘되고, value값 가져오는거 확인했습니다!

Feature/검색 인풋 공통컴포넌트 구현 #240

---

src/components/Card/PostingCard.interface.ts
src/components/Card/PostingCard.tsx
src/components/Table/GridTable.tsx

- #130, #134
- 그리드뷰 컴포넌트 구현하였습니다.
- 아직 세부적인 기능은 구현 안 된 상태고, 데이터 받아와서 띄워주는 것만 가능하도록 처리해두었습니다.
- StandardTable의 row 받아오는 형식과 동일하게 row 넣어주면 그리드 뷰로 띄워주도록 해두었습니다. (row에는 그리드 뷰에 필요한 props가 있어야합니다.)
- 30분
- 컴포넌트 분리해둔 방식 괜찮은 지, 타입 적용한 부분 제대로 해두었는 지 중점적으로 봐주세요!
(row 다 적으면 너무 길어져서 3개만 남겨두겠습니다.)
```tsx
import GridTable from '@components/Table/GridTable';
interface ExampleRow {
id: number;
no: number;
title: string;
writer: string;
writerId: number;
writerThumbnailPath: string | null;
size: number;
visitCount: number;
commentCount: number;
registerTime: string;
isNotice: boolean;
isSecret: boolean;
isTemp: boolean;
category: string;
categoryId: number;
thumbnailPath: string | null;
}
const rows: ExampleRow[] = [
{
id: 356,
no: 1,
title: '안녕하세요', …
```

Feature/테이블 그리드뷰 #130

---

src/components/Input/StandardInput.tsx
src/constants/muiTheme.ts

- #282 
- close #300 
-  input border색을 pointColor로 변경시켜줌
1분

Feature/인풋공통컴포넌트 border색 포인트컬러로 변경

---

src/pages/SignUp/SignUp.tsx
src/router/useMainRouter.tsx

- Close #302
- 라우터에 회원가입 페이지 추가
- 0.1분

Feature/라우터에 회원가입 페이지 추가 #302

---

src/components/Layout/Header/Header.tsx
src/components/Layout/Sidebar/Sidebar.tsx
src/components/Navigation/CategoryNav.tsx
src/components/Navigation/SubCategoryNav.tsx
src/constants/category.ts
src/constants/keeperTheme.ts

- Close #201 
- 추후 작업 #271 #272 #273 #278
- 사이드바 카테고리 띄우기
- 사이드바 상위 카테고리 클릭 시 하위 카테고리 펼쳐지도록 구현였습니다.
- 아직 클릭시 경로 이동이나 디자인 요소는 입히지 않고 단순 카테고리, 서브 카테고리 띄워주는 것만 구현한 PR입니다.
- 10분
- 중점 리뷰 요구 부분 커멘트로 달아두겠습니다.

Feature/사이드바 제작 #201

---

src/components/Modal/WarningModal.tsx

- Close #334
- 모달 제목으로 아이콘과 주의 텍스트가 들어가는 모달입니다.
- 5분
- #336 선행 PR입니다! 먼저 리뷰 후 이 PR 리뷰 부탁드립니다!
- 이 PR은 [feat : 주의 모달 구현](https://github.com/KEEPER31337/Homepage-Front-R2/commit/4b2ff5c862c5352e58d65f1797d5e0edb3e30e0b) 이 커밋만 보면 됩니다!
```tsx
const [modalOpen, setModalOpen] = useState(false);
return (
<div>
<OutlinedButton onClick={() => setModalOpen(true)}>추가</OutlinedButton>
<WarningModal
open={modalOpen}
onClose={() => setModalOpen(false)}
actionButtonName="확인"
onActionButonClick={() => {
// TODO
}}
>
내용~~ㅁㄴㅇㄹㅁㅇㄴㄹ
</WarningModal>
</div>
);
};
```

Feature/주의 모달 공통 컴포넌트 #334

---

package-lock.json
package.json

- Close #371
- form 관련된 처리를 간편하게 할 수 있는 라이브러리로 `react hook form` 설치
- 0.1분 소요 예정

Feature/react hook form 설치 #371

---

src/constants/muiTheme.ts
tailwind.config.js

- #392 해당 풀리퀘가 선행입니다! 먼저 봐주시면 감사하겠습니다!
- close #390
- mui 버튼 컴포넌트 font size 1rem으로 변경
- 30초

Feature/mui 버튼 컴포넌트 font size 1rem으로 변경 #390

---

tailwind.config.js

#383
#310 
tailwind 커스텀 파이엘 오랜지 색상 추가했습니다!
0.5초

Feature/subOrange 커스텀 색상 추가

---

src/pages/senimarAttend/Card/MemberCardContent.tsx

#310 
코드 옳을때만 출석 상태 뜨도록 했습니다~ 
30초

Feature/코드 옳을 시에만 출석상태 뜨도록 함

---

src/pages/Game/Game.tsx

- Close #402
- 게임 규칙 버튼 클릭 시 각 탭 게임별 규칙 모달에 뜰 수 있도록 해주었습니다.
- `gameList`에 `rule` 속성을 추가해서 모달의 childred으로 해당 내용 전달하도록 처리해주었습니다.
- 게임 규칙은 게임 프로젝트 readme에 작성될 내용 가져올 거라 지금은 null로 넣어두었습니다!
- 5분
(실제 baseball 규칙과는 무관합니다.)
```tsx
const gameList = [
{
id: 1,
label: 'BASEBALL',
rule: (
<>
<div>
<IconButton color="secondary" aria-label="add an alarm">
<VscCheck size={20} className="fill-pointBlue" />
</IconButton>
300포인트를 배팅하여 랜덤하게 포인트를 얻을 수 있습니다!
</div>
<div>
<IconButton color="secondary" aria-label="add an alarm">
<VscCheck size={20} className="fill-pointBlue" />
</IconButton>
하루 최대 5번 시도할 수 있습니다.
</div>
</>
),
},
];
```

Feature/게임 설명 모달 구현 #402

---

src/components/Navigation/SubCategoryNav.tsx
src/constants/keeperTheme.ts
tailwind.config.js

- Close #273
- 사이드바 디자인 일부 추가로 적용해주었습니다.
- 예상 소요 시간 `2분`
- 사이드바 넓이 상수로 지정해둔 게 config 파일에서는 import가 되지 않더라구요! 하나의 값만 수정하면 다 바뀌도록 하고 싶은데 좋은 방법 있으면 알려주세요~!
- @pipisebastian 추가적으로 디자인 수정할 부분 있으면 알려주세요!

Feature/사이드바 디자인 적용 #273

---

src/components/Button/ActionButton.tsx

- close #357 
- mode에 따라 아이콘 다르도록 
- 3분
- 3항 연산자로 구현했는데, eslint에서 중첩하지 말라는 에러가 뜹니다! 근데 이것말고 깔끔한 방법이 보이지 않아,
무시하고 3항 연산자 사용했는데 더 좋은 방법있다면 추천 부탁드립니다!

feat : 추가, 삭제, 수정 버튼 제작

---

src/api/dto.ts
src/api/postApi.ts
src/components/Editor/StandardEditor.tsx
src/components/Input/StandardInput.tsx
src/components/Modal/ActionModal.tsx
src/components/Uploader/FileUploader.tsx
src/components/Uploader/ImageUploader.tsx
src/constants/errorMsg.ts
src/pages/board/BoardList.tsx
src/pages/board/BoardView/BoardView.tsx
src/pages/board/BoardView/Section/PostSection.tsx
src/pages/board/BoardWrite/BoardWrite.tsx
src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
src/router/useMainRouter.tsx

- #430 
- Close #511 
- 게시글 작성 세부적인 기능들 구현 마무리 하였습니다.
- 파일, 이미지 API 전달하도록 추가 작업해주었습니다.
- 필수값, 글자수 제한 있는 부분에 대한 처리 해주었습니다.
- 관련된 공통 컴포넌트 부분 일부 수정이 있었습니다.
- 이미지 업로더
- 공통 컴포넌트에 이미지 규격을 틀에서 벗어나지 않도록 처리해주었습니다.
- 기본 로고 이미지 기본적으로 아래에 깔려있도록 처리해주었습니다.
- 클릭 가능 영역임을 가시적으로 보여주기 위해 마우스 hover 시 투명도 달라지도록 처리하였습니다.
- 액션모달
- 액션 버튼 비활성화 가능하도록 확장해주었습니다.
- 이외에도 focus라거나 기본값, 상황에 따른 disabled 처리 등등 세세한 부분 작업하였습니다.
- 예상 소요 시간 20분

Feature/게시글 작성 세부 기능 구현 #430

---

package-lock.json
package.json
src/pages/Game/Baseball/Baseball.tsx
src/pages/Game/Baseball/api/baseballApi.ts
src/pages/Game/Baseball/api/baseballDto.ts
src/pages/Game/Baseball/components/CountdownBar.tsx
src/pages/Game/Baseball/components/InfoModal.tsx
src/pages/Game/Baseball/components/NoticeEnd.tsx
src/pages/Game/Baseball/components/NumberInput.tsx
src/pages/Game/Baseball/components/PointInfo.tsx
src/pages/Game/Baseball/components/TurnInfoBoard.tsx
src/pages/Game/Baseball/components/TurnInfoCard.tsx
src/pages/Game/Baseball/screens/GamePlay.tsx
src/pages/Game/Baseball/screens/GameStart.tsx
src/pages/Game/Game.tsx
src/tailwind.css
tailwind.config.js

- Close #403
- https://github.com/KEEPER31337/Game-Baseball 이 프로젝트에서 작업한 야구 게임 넣어주었습니다.

Feature/게임 불러오기

---

src/pages/admin/LibraryManage/LibraryManage.tsx
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx

- Close #352
- 도서관리 tab 추가
- BookManageTab부분은 원래 LibraryManage에서 코드만 긁어온거라, 신경안쓰셔도 됩니다!
- 1분, 파일명 괜찮은지 확인 부탁드립니다!
-

feat : 도서관리페이지 tab추가 및 tab 컴포넌트 작성

---

src/api/dto.ts
src/components/Pagination/StandardTablePagination.tsx
src/pages/board/BoardList/BoardList.tsx
src/pages/board/BoardList/SearchSection/BoardSearchSection.tsx

- Close #133
- 게시판 목록 조회 시 검색 가능하도록 처리해주었습니다.
- `useSearchParams` 사용하여 검색 기능 구현하였습니다.
- page 정보와 검색 정보 모둘 url params로 관리되는데 set해주는 부분이 달라서 전환이 아닌 업데이트 처리되도록 page 부분에서는 searchparam 객체도 포함하도록 넣어주었고, 검색 부분에서는 검색하면 첫번째 page로 이동되도록 처리하였습니다.
-  예상 소요 시간 `5분`

Feature/게시판 검색 기능 구현 #133

---

src/pages/Library/Library.tsx
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx

- #547 부터 봐주세요!
- #548 
- 검색창 ui만 구현했습니다.
- 기능은 백엔드에 질문 하나 여쭤본 상태라, 추후에 다른 이슈로 넣겠습니다
- 다른데서도 해당 브랜치 풀받아야해서, p1으로 올리겠습니다!
>  0.1분

Feature/도서관리 탭 search section 추가 #548

---

src/api/dto.ts
src/api/libraryApi.ts
src/api/libraryManageApi.ts
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx

- Close #550
- #547 #549 선행 리뷰부탁드립니다..!
- 도서관리 - 책목록 가져오기 api 연결했습니다.
- `BookInfo`는 도서페이지에서 쓰이는 타입이고, 그걸 확장한 `ManageBookInfo` 타입 사용했습니다
- 5분.

Feature/책목록가져오기 api 연결 #550

---

src/api/dto.ts
src/api/libraryManageApi.ts
src/pages/admin/LibraryManage/Modal/AddBookModal.tsx
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx

- Close #551
- #557 선행 리뷰부탁드립니다..!
- 도서추가 모달창 기능 구현했습니다. 코멘트 남기겠습니다
- 3분

Feature/도서추가 모달 기능 구현 #551

---

src/api/postApi.ts
src/components/Table/StandardTable.tsx
src/pages/board/BoardList/BoardList.tsx

- #556, #261
- 공지글 목록 추가하고, 비밀글 앞에 아이콘 붙여줬습니다.
- `10분`
- 나머지 더 작업할 사항 있는데 일단 요약에 적어둔 것만 PR 먼저 올립니다!
- 테이블 상단에 row 고정할 수 있도록 기능 확장하였습니다. 코드 중복되는 부분도 있어서 리팩토링 하고 싶긴한데 빠른 작업이 우선 인 것 같아서 일단 중복 코드로 작성하였습니다! 깔끔한 코드 제안해주실 분 있으면 적극 환영입니다!

Feature/게시판 남은 작업 처리

---

src/api/dto.ts
src/api/libraryManageApi.ts
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx

> Close #576 
- 도서삭제 기능 추가
- react query 잘못 쓴 부분 수정
- 코멘트로 설명달겠습니다
- 5분

feat : 도서삭제 기능 추가

---

src/pages/Library/Card/BookCard.tsx

- Close #602
-  도서페이지 썸네일 적용했씁니다!
- 0.5분

feat : 도서페이지 썸네일 적용

---

src/components/Card/FixedPostingCard.tsx
src/components/Card/PostingCard.interface.ts
src/components/Card/PostingCard.tsx
src/pages/board/BoardList/BoardList.tsx

- Close #612
- 1일 내에 작성된 글에 대한 최신글 표기 추가해주었습니다.
- 7분
- 선행 PR #609  먼저 리뷰 부탁드립니다! 이 PR은 [feat : 테이블에 최신글 표시 추가](https://github.com/KEEPER31337/Homepage-Front-R2/commit/af62b9bb72936d26184bd22bb51bbc158f97a50c) 해당 커밋부터 보면 됩니다!

Feature/최신글 n 표시해주기 #612

---

src/api/dto.ts
src/api/dutyManageApi.ts
src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx

* #607
* [회원 목록 조회 API](http://13.209.6.87:8081/docs/member/member.html#_%ED%9A%8C%EC%9B%90_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C%EA%B2%80%EC%83%89) 의 변수명 변경 적용 (`memberName` -> `realName`)
* `1분`

feature/직책관리 페이지 백엔드 API 변수명 변경 적용

---

src/components/Layout/Container/FullContainer.tsx
src/pages/Profile/Profile.tsx
src/router/useMainRouter.tsx

- #610
- 레이아웃 full container로 변경했습니다
- 1분

feat : 레이아웃 full container로 수정

---

src/components/DatePicker/StandardDatePicker.tsx
src/constants/errorMsg.ts
src/pages/SignUp/Section/SignUpSecondInputSection.tsx
src/pages/SignUp/SignUp.recoil.ts
src/pages/SignUp/SignUp.tsx
src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx

- Close #296
- 프로필 정보 단계 기능 react hook form 사용해서 유효성 구현해주고, valid한 상태일 때 다음 단계로 넘어갈 수 있도록 처리해주었습니다.
- 예상 소요 시간 15분
- 인풋 에러 발생 + focus하지 않은 상태일 때 라벨 위치가 아래로 내려가 있는데 #638 에서 보완할 예정입니다!

Feature/회원가입 프로필 정보 단계 기능 구현 #296

---

src/api/dto.ts
src/api/signUpApi.ts
src/components/Input/EmailAuthInput.tsx
src/components/Input/StandardInput.tsx
src/components/Input/TimerInput.tsx
src/pages/SignUp/Section/SignUpSecondInputSection.tsx
src/pages/SignUp/Section/SignUpThirdInputSection.tsx
src/pages/login/Search/SearchID.tsx
src/pages/login/Search/SearchPWFirstStep.tsx
src/utils/validateEmail.ts

- Close #297
- 이메일 중복 확인, 인증 코드 이메일 발송, 회원가입 처리 하였습니다.
- ~선행 PR #639 먼저 리뷰 부탁드립니다!~ 머지 완료
- `useEffect` 부분이나, `enabled`, `disabled` 등의 부분 처리가 동작 흐름에 맞게 처리되어 있는 지 위주 봐주시면 좋을 것 같습니다!

Feature/회원가입 이메일 인증 단계 기능 구현 #297

---

package-lock.json
package.json
src/api/dto.ts
src/pages/Profile/Tab/AttendanceTab.tsx

- #554
- UI 구성했습니다. 기능 구현은 추후 작업으로 PR 끊어 올리겠습니다.
- [nivo Calendar](https://nivo.rocks/calendar/) 사용하여 캘린더 구성하였습니다.
- 5분
- 아직 기능 없는 깡통입니다. 구성만 봐주세요!

Feature/내 프로필 출석부 탭 구현 #554

---

src/pages/Game/Baseball/api/baseballApi.ts

- Close #644
- 게임 참가 포인트 부족할 때 에러 토스트 메시지로 띄워주도록 처리해주었습니다.
- 1분
- 지금은 게임 한 개지만 게임 늘어난다고 보면 포인트 부족 관련 부분이 공통적으로 다 처리해야하는 부분일 것 같아서 게임 화면 내부에 구성 하지 않고 토스트 메시지로 띄워줬는데 괜찮나요?~?
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/67a7eaaa-1be9-4f64-9be9-69d85eaeecb3

Feature/게임 포인트 부족할 때 관련해서 처리 #644

---

src/components/Layout/Sidebar/Sidebar.tsx
src/pages/Profile/Profile.tsx
src/pages/Profile/Tab/AttendanceTab.tsx

- #554
- 출석부 탭 반응형 적용하였습니다.
- 예상 소요 시간 5분
- `md:`, `lg:`, `sm:`, `xl:` 달려있는 부분 위주로 봐주시면 될 것 같습니다!
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/26e62978-1055-476c-8b28-40ca7715931b

Feature/내 프로필 출석부 탭 구현 - 반응형 #554

---

src/api/meritApi.ts
src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx
src/pages/admin/MeritManage/Tab/UserMeritTab.tsx

#653 
회원 상벌점 내역 모달 입니다
해당하는 회원의 상벌점 내역을 보여줍니다
5분

Feature/상벌점 페이지 회원상벌점내역 모달 #653

---

src/components/Typography/TextTimer.tsx
src/pages/SignUp/Section/SignUpThirdInputSection.tsx
src/pages/login/Search/SearchID.tsx
src/pages/login/Search/SearchPWFirstStep.tsx

- Close #298 
- 인증 메일 재발송, 다른 이메일로 인증 기능 구현하였습니다.
- 5분

Feature/회원가입 인증 메일 안내 모달 기능 구현 #298

---

src/components/Layout/Container/FitContainer.tsx
src/components/Layout/Container/FullContainer.tsx

- Close #703
- 헤더 높이에 따른 레이아웃 반응형 적용했습니다.
- 1분

feat : 헤더 높이에 따른 레이아웃 반응형 적용

---

src/api/dto.ts
src/api/seminarApi.ts
src/pages/admin/SeminarManage/Modal/AddSeminarModal.tsx
src/pages/admin/SeminarManage/Modal/DeleteSeminarModal.tsx
src/pages/senimarAttend/Card/BossCardContent.tsx
src/pages/senimarAttend/Card/MemberCardContent.tsx
src/pages/senimarAttend/SenimarAttend.tsx

- #672 
- 
- 세미나 추가, 삭제 기능 구현
- 추가, 삭제시 완료되었다는 토스트 메시지는 추후에 추가 예정
- 백엔드 수정사항으로 응답 필드 네이밍 변경 
- 5

feat : 세미나 추가, 삭제 기능 구현

---

src/api/pointApi.ts
src/pages/Profile/Modal/SendPointModal.tsx
src/pages/Profile/Section/ProfileSection.tsx

#682 
포인트 선물 모달입니다.
포인트 선물을 위한 모달입니다.
5분
useForm 사용했는데 제대로 사용됬는지 확인부탁드립니다.

Feature/포인트선물하기 #682

---

src/api/dto.ts
src/api/seminarApi.ts
src/pages/admin/SeminarManage/SeminarManage.tsx
src/pages/senimarAttend/Card/MemberCardContent.tsx
src/pages/senimarAttend/Status/SeminarAttendStatus.tsx

- #382
- 세미나 출석 목록 받아와 테이블에 적용해주었습니다.
- column이 세미나 출석, 삭제됨에 따라 변하기 때문에 동적으로 동작 가능하도록 처리해주었습니다.
- 10분
- @pipisebastian 세미나 추가/삭제에 따른 조회 목록 변경 잘 되는 거 확인 되었습니다!
- 테이블 관련 동작(column 고정, 가로 스크롤)은 아직 적용 안 된 상태입니다! 이 PR 머지되면 작업 예정!

Feature/세미나 전부 조회 기능 #382

---

src/api/libraryApi.ts
src/pages/Library/Library.tsx
src/pages/Library/Status/BorrowStatus.tsx

- Close #706
- 도서검색 반응형 적용
- 알고보니 도서신청 버튼누를때 도서목록 새로받고, 빌린 책 목록을 다시 받아와야하는데 빼먹었더라구요.. 그래서 추가해줬습니다
- 1분
-

refactor : 도서검색 반응형 및 invalidateQueries문 추가

---

src/components/Input/SearchInput.tsx
src/components/Section/SearchSection.tsx

- Close #719
인풋 관련 공통 컴포넌트 텍스트, width 관련 반응형 처리해주었습니다.
- 5분

feat : SearchSection 컴포넌트 반응형 처리

---

src/api/dto.ts
src/pages/Profile/Tab/AttendanceTab/Section/AttendanceInfoSection.tsx

- #693
- 총 출석일 api에서 받아와 반영해주었습니다.
- 현재 실제 출석된 일수와 api 응답으로 오는 총 출석일이 다른 이슈가 있어 백엔드 담당자님께 문의드려놓은 상태입니다!

feat : 총 출석일 반영

---

src/components/Card/FixedPostingCard.tsx
src/components/Card/PostingCard.tsx
src/components/Table/GridTable.tsx
src/components/Table/StandardTable.interface.ts
src/components/Table/StandardTable.tsx
src/pages/board/BoardList/BoardList.tsx

- Close #717
- Close #725 
- 게시글 목록 조회(게시판) 리스트뷰, 그리드뷰 반응형 적용하였습니다.
- 테이블 column 너비 조정 가능하도록 확장하였습니다.
- 10분
- 그리드뷰 모바일 크기일 때 공지 width 좀 더 늘릴까 싶기도 한데 일단 이 PR에서는 처리 안 할 예정입니다!
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/82056bb5-12c9-4152-afdd-dca38931741f
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/90507b42-4e3b-4e22-a80e-3280ed22f0e5

Feature/게시글 목록 조회 반응형 #717

---

src/components/Input/TimerInput.tsx
src/components/Modal/MailAuthenticationModal.tsx
src/pages/SignUp/SignUp.tsx

- Close #732
- 회원가입 반응형 적용했습니다.
- 5분
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/918757a1-c7ad-45be-bfc7-6e91df977674

Feature/회원가입 반응형 #732

---

src/components/Editor/StandardEditor.tsx
src/pages/board/BoardWrite/BoardWrite.tsx
src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx

- #734
- 게시글 작성 페이지 반응형 적용
- 5분
- 모바일에서 이미지, 첨부파일 업로드 안 되는데 이후 #735 에서 처리 예정입니다.
- 모바일에서 editor에 `autofocus` false임에도 포커스되는 이슈가 있습니다. 추후 별도로 처리 예정입니다!
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/5e37fe60-ed80-415c-8bcc-1ba3a9ce88c6

Feature/게시글 작성 페이지 반응형 #734

---

src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx

#663 
SettingMeritTypeModal Props 개선
SettingMeritTypeModal Props를 변경했습니다.
- open을 입력받고 status는 edit 일 경우에만 받습니다.
- edit을 props로 받습니다.
5분

refactor : 상벌점 페이지 개선

---

src/components/Pagination/StandardTablePagination.tsx
src/components/Table/StandardTable.tsx

- Close #726
- 테이블 overflow 시 스크롤 가능하도록 처리
- sm 이하 사이즈일 때 페이지네이션 크기 작아지도록 처리
- ~선행 PR #727 먼저 리뷰 부탁드립니다!~ 머지 완료
- 예상 소요 시간 `7분`
```tsx
const boardColumn: Column<BoardRow>[] = [
{ key: 'no', headerName: '번호', width: '300px' },
{ key: 'title', headerName: '제목', width: '300px' },
{ key: 'writerName', headerName: '작성자', width: '300px' },
{ key: 'registerTime', headerName: '작성일', width: '300px' },
{ key: 'visitCount', headerName: '조회수', width: '300px' },
{ key: 'likeCount', headerName: '추천수', width: '300px' },
];
```
고정된 column width에 따라 overflow 시 스크롤 적용
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/a008ae09-f15d-4cb8-a56f-524ec9fce92d

Feature/테이블 반응형 관련 처리 #726

---

src/pages/board/BoardView/BoardView.tsx
src/pages/board/BoardView/Card/CommentCard.tsx
src/pages/board/BoardView/Card/CommentCardFooter.tsx
src/pages/board/BoardView/Card/CommentCardHeader.tsx
src/pages/board/BoardView/Card/CommentWriteCardAction.tsx
src/pages/board/BoardView/Card/ReplyCard.tsx
src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
src/pages/board/BoardView/Section/CommentSection.tsx
src/pages/board/BoardView/Section/PostSection.tsx

- #730
- 게시글 조회 페이지 반응형 적용하였습니다.
- 5분
- 첨부파일 목록 테이블 부분은 아직 반응형 적용하지 않은 상태입니다. #729 머지되면 이후 처리 예정입니다.
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/19df35e5-14e0-4446-99fc-c0871d7d6778

Feature/게시글 조회 페이지 반응형 #730

---

src/pages/login/Login.tsx

- Close #659
- 기획상 제거된 로그인 상태 유지 체크박스 제거하였습니다!
- 예상 소요 시간 2분

feat : 로그인 상태 유지 제거

---

src/pages/admin/DutyManage/Button/DutyProfileButton.tsx
src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx

#745
AutoComplete로 직책을 수정할 수 없는 문제 픽스
- jobInfo가 해당 담당자가 없는 경우 정의되지 않는 문제 -> convertJobName을 이용하여 프론트에서 jobId 정의
- 해당 담당자가 없는 경우 deleteJob에서 오류 발생 -> if문으로 걸러줌
- AutoComplete 선택안됨 -> !-z-10 제거 (다른 곳도 필요할 듯....)
- 직책 담당자가 없는 경우 "기" 만뜨는 문제 -> 조건부 렌더링 처리
2분
생각보다 큰 수정사항이 없습니다.
직책 설명 툴팁 아직 내용이 "굉장히 굉장히 굉장히 ... 긴 문자열" 로 들어가 있는데 넣을 내용 알고 있으신분 알려주세요...

fix : autocomplete 문제

---

src/pages/login/Login.tsx
src/pages/login/Search/SearchPWSecondStep.tsx

- Close #624
- 로그인 페이지 비밀번호 타입 •••• 형태로 뜨도록 처리해주었습니다.
- 3분

feat : 비밀번호 타입 적용

---

src/api/dto.ts
src/pages/Study/Accordion/StudyAccordion.tsx
src/pages/Study/Accordion/StudyAccordionBody.tsx
src/pages/Study/Accordion/StudyAccordionHeader.tsx
src/pages/Study/Modal/StudyModal.tsx
src/pages/Study/Study.tsx

- Close #757
- #155 
- 스터디 추가 시에 스터디원 dto가 안 맞아서 에러 발생하는 이슈가 있었는데 dto 맞춰줘서 해결하였습니다.
- 링크의 경우 기본값을 빈 문자열로 지정해뒀어서 빈문자열 받아올 경우 실제로 링크가 없는 건데 UI에 띄워주고 있었어서 기본값 null로 변경 후 있는 링크만 보이도록 처리해주었습니다.
- 스터디원 링크의 경우 아코디언에 띄워주는 거 처리 안 된 상태였는데 처리해주었습니다.
- 버튼 배치 변경했습니다.
- 10분

Feature/스터디 남은 기능 구현

---

src/api/dto.ts
src/components/Input/AutoComplete.tsx
src/pages/Study/Accordion/StudyAccordion.tsx
src/pages/Study/Accordion/StudyAccordionBody.tsx
src/pages/Study/Modal/StudyModal.tsx
src/pages/Study/Study.tsx

- Close #699, Close #155
- 스터디원 수정에 필요한 작업들 해주었습니다.
- 10분
- 코멘트 남겨두겠습니다!
- 현재 스터디 모달에 focus가 링크에 가있고, 제목 내용에 바로 에러 문구 뜨고 시작하는 이슈가 있는데 이후 별도 이슈에서 해결할 예정입니다!

Feature/스터디원 수정 #699

---

src/pages/Library/Card/BookCard.tsx

#741
- Close #741 
- 
- 도서 검색 글자수 overflow처리
- CSS 더좋은방법 있다면 추천부탁드립니닷,,!
- 2분
-

feat : 도서검색 글자수 over 처리

---

src/api/studyApi.ts
src/pages/Study/Accordion/StudyAccordion.tsx
src/pages/Study/Modal/StudyDeleteModal.tsx

- Close #765 
- 스터디 삭제 기능 추가
- 은지님이 틀 거의 다 짜주셔서 연결만 했습니당!
- 3분

feat : 스터디 삭제 기능 추가

---

src/components/Input/EmailAuthInput.tsx
src/pages/Profile/Modal/EditAccountModal.tsx
src/pages/SignUp/Section/SignUpThirdInputSection.tsx
src/pages/login/Search/SearchID.tsx
src/pages/login/Search/SearchPWFirstStep.tsx

- Close #629
- 이메일 전송 상태에 따른 처리 해주었습니다.
- 이메일 전송중 circle progress 띄우기
- 이메일 전송 완료 후 체크 아이콘 띄우기
- 로그인, 회원가입 페이지, 계정정보 수정 모달에 적용하기
- 예상 소요 시간 7분
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/1378263e-c0cf-497d-a28c-6c6944e01bdb
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/b52679cc-af7c-4658-8c92-c51e24ec40ad

Feature/이메일 전송중과 완료 시 아이콘 띄우기 #629

---

src/components/Uploader/FileUploadList.tsx
src/components/Viewer/FileViewer.tsx

- Close #734 
- Close #730
- 첨부 파일 관련 반응형 처리했습니다!
- 5분
|게시글 작성|게시글 조회|
|---------|----------|
|<img width="397" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/a0d48191-0ca6-46f0-8e0b-9dc722c1f89c">|<img width="379" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/c20f0dd0-5b3e-4e76-b117-e737dfd61aae">|

Feature/첨부 파일 관련 반응형 처리

---

src/components/Table/StandardTable.tsx
src/pages/admin/LibraryManage/Tab/BookManageTab.tsx
src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx
src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx

- Close #772 
- 도서관리 반응형 +  표 다듬기(width)
- 3분. width의 경우 적당히 봐가면서 줬습니다!
- 이거 머지되면 바로 슬랙에 검토요청하겠습니다!

Feature/도서관리 반응형 #772

---

src/pages/admin/LibraryManage/LibraryManage.tsx
src/router/useMainRouter.tsx

- Close #768
- 
- 탭별 url 추가
- 0.5분

feat : 도서관리 탭별 url 추가

---

src/api/dto.ts
src/pages/rank/Rank.tsx
src/pages/rank/TopCard.tsx

#780 
랭킹페이지 QA 반영입니다
api에 맞춰 변수명 변경
빈리스트 처리
반응형 처리
10분

Feature/랭킹페이지 수정 #780

---

src/pages/login/Login.tsx

fix : 로그인 실패 알림

---

src/api/postApi.ts
src/pages/board/BoardView/BoardView.tsx
src/pages/board/BoardView/Card/CommentCard.tsx
src/pages/board/BoardView/Card/CommentCardFooter.tsx
src/pages/board/BoardView/Modal/WarningDeductPointModal.tsx
src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx
src/pages/board/BoardView/Section/CommentSection.tsx
src/pages/board/BoardView/Section/PostSection.tsx

- #789
- 게시글 조회 페이지 QA 받은 거 버그 픽스 진행하였습니다.
- 커밋 참고 부탁드립니다.
- 7분
- 커밋마다 별도의 처리들이라서 커밋 단위로 확인하면 편할 것 같습니다.
- 비밀글 관련 추가로 픽스할 게 있는데 다음 PR로 올리겠습니다!

Feature/게시글 조회 페이지 버그 픽스 #789

---

src/mocks/DutyManageApi.ts
src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx

- #798 
- #802 코드 리뷰 반영
- 전산관리자는 툴팁이 안 보이도록 변경
- 회장 툴팁이 안 뜨는 에러 해결
-` 1분`

fix : 직책관리 페이지 버그 픽스 코드 리뷰 반영

---

src/api/meritApi.ts
src/components/Input/RadioButton.tsx
src/components/Selector/Selector.tsx
src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx
src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx
src/pages/admin/MeritManage/Tab/MeritLogTab.tsx
src/pages/admin/MeritManage/Tab/UserMeritTab.tsx

상벌점 페이지 QA 반영 입니다.
- 회원별 내역 조회 isMerit 처리
- 입력없이 추가시 에러문구 -> 추가 버튼 비활성화 처리
- 점수에 0 제거 -> 추가로 기본값은 1로 변경했습니다.
- 회원별 내역 조회에 내역 삭제 기능 추가 -> 모달 위에 모달이긴한데 확인은 필요할 듯 하여 사용했습니다.
- 상벌점 부여 기수 그룹 추가
- 상벌점 부여 사유에 점수 및 색 추가 -> Selector Props type 변경했습니다
- 회원별 내역 조회 모달 사이즈 lg로 변경 -> 크게 보는게 좋을 듯 하고 기존 sm 사이즈는 내역상세가 잘리는 문제가 있었습니다.
5분

Feature/상벌점 페이지 버그픽스

---

src/pages/home/Activity.tsx
src/pages/home/Home.tsx

화면은 줄일때 메인화면의 내용이 잘리는 문제 해결
- w-full을 주어 잘리는 문제를 해결했습니다
- 이미지에 h-full, object-cover을 주어 화면을 채우도록 했습니다.
1분

Feature/메인페이지 반응형 QA

---

src/pages/rank/Rank.tsx

출석랭킹에러fix
기존에 id를 rank값으로 했었는데 rank가 동일할때 문제가 발생하여 index 기준으로 변경하였습니다.
1분

fix : 출석랭킹에러fix

---

src/pages/Profile/Section/BadgeSection.tsx

- Close #819
출제자일때 뱃지 안보이도록 처리

fix : 출제자일때도 뱃지 안보이도록

---

src/pages/Profile/Section/BadgeSection.tsx
src/pages/Profile/Section/FollowList.tsx
src/pages/Profile/Section/ProfileSection.tsx
src/pages/Profile/Tab/BookTab/BookTab.tsx
src/pages/Profile/Tab/BookTab/Card/BookCard.tsx

- Close #824
- 도서카드 넘버링 + 디자인 수정
- 뱃지 안넘어가도록
- 팔로워리스트 부분 디자인 수정
- 사진첨부합니다..

Feature/프로필 페이지 버그 픽스 #824

---

src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx

- Close #825
- 높이 고정 및 scroll 추가

Feature/활동인원 관리 버그 픽스 #825

---

src/api/dto.ts
src/api/seminarApi.ts
src/components/Table/StandardTable.interface.ts
src/components/Table/StandardTable.tsx
src/pages/admin/SeminarManage/SeminarManage.tsx

- Close #307, Close #786
- 테이블 우측 column 고정 기능 확장하고, 세미나 관리 테이블 총 횟수들 추가했습니다.

Feature/세미나 관리 테이블 관련 처리 #786

---

src/pages/Profile/Tab/BoardTab/Table/MemberBoardTable.tsx

프로필 작성글 버그픽스
작성글조회 페이지키에 유저아이디를 넣었었는데 표에 빼먹었습니다. 추가후 정상작동 확인했습니다.
1분

fix : pagenation key 변경

---

src/components/Layout/Sidebar/Sidebar.tsx

- Close #831
- 버그 및 개선사항 제보 버튼 클릭 시 새 이슈 생성 url로 새 탭 띄워주도록 하였습니다.
- 예상 소요 시간 1분

Feature/버그&불편사항 제보 링크 추가 #831

---

src/pages/senimarAttend/Card/MemberCardContent.tsx
src/pages/senimarAttend/Input/SeminarInput.tsx
src/pages/senimarAttend/SenimarAttend.tsx
src/pages/senimarAttend/seminarAttend.recoil.ts

- Close #792 
- 출석 불가능한 세미나 임에도 출석 버튼 클릭이 가능하던 버그 fix했습니다.
- 세미나 출석 코드 인풋에 포커스가 없어서 입력 가능 상태인지 알아보기 어려워서 포커스 처리해주었습니다.
- 출석 시도 횟수 이상하게 뜨는 버그 픽스했습니다. (출석 시도 횟수 지금은 프론트에서 처리하고 있는데, 나중에 백엔드에서 받아오도록 수정해야할 것 같아요!)
- 세미나 쪽 코드를 많이 바꿔서 혹시나 이상 없는 지 한 번 검토 부탁드립니다!

Feature/세미나 출석 페이지 버그 픽스 #792

---

src/pages/admin/LibraryManage/Modal/UploadBookModal.tsx
src/pages/admin/LibraryManage/Selector/TotalBookNumberSelector.tsx

- close #851 
- 해당 내용으로 반영했습니다
- 0.1 분

Feature/백엔드 수량으로 일치 #851

---

src/components/Layout/Header/Header.tsx
src/components/Layout/Sidebar/Sidebar.tsx
src/constants/keeperTheme.ts
tailwind.config.js

- Close #850, #258
- 키퍼 테마로 커스텀된 너비들 상수로 적용해주었습니다.
**(✅는 변경 후 정상동작(색상 이상 없는 지) 확인한 사항입니다!)**
- 사이드바, 헤더, 컨테이너
- ✅  변경후 사이즈 변동 없음 확인하였습니다.
- 예상 리뷰 소요 시간 `2분`

Feature/너비 하드코딩 된 부분 수정 #850

---

src/api/authApi.ts

- Close #859
- 401 에러 발생 시에도 로그아웃 처리

Feature/로그아웃 401 에러 처리

---

src/api/pointApi.ts

- Close #868
Point Api 쿼리키 포멧 통일
querykey factor에 맞게 수정하였습니다
1분

refactor : point Api querykey factor

---

src/api/aboutApi.ts

- Close #864 
About Api 쿼리키 포멧 통일
기존의 따로 들어갔던 type을 쿼리키 함수에 추가했습니다
1분

refactor : about api 쿼리키 포멧 통일

---

.vscode/settings.json
src/pages/Study/Accordion/StudyAccordion.tsx

- close #839 
- 429 Error : api를 너무 많이 요청해서 발생하는 문제였음.
- accordion 의 옵션을 mountOnEnter: true로 설정
- 리뷰 예상 시간 : `1분`

fix: 스터디 상세 정보 관련 버그 수정
