src/tailwind.css
- #168
- default로 적용되는 폰트 지정
- 디자인 회의때 지정한 `IBM Plex Sans KR` 폰트를 별도의 유틸리티 클래스를 작성하지 않아도 default로 적용되도록 하였습니다.
- `IBM Plex Sans KR` 대체 폰트로 tailwind 공식문서 예제와 동일하게 시스템 폰트와, (tailwindcss default 폰트인) sans 폰트도 같이 넣어주었습니다.
- 폰트 잘 적용되는 거 확인하였습니다.
`1분`, 가볍게 보고 넘어가셔도 될 것 같습니다.
=> Feature/tailwindcss 기본 폰트 지정 #168

tailwind.config.js
- #168
tailwind config 파일 내 폰트 사이즈 커스텀 작성 
h1: '28pt',
h3: '20pt',
paragraph: '16pt',
small: '12pt',
폰트 사이즈 추가
x
=> Feature/tailwindcss 폰트 사이즈 커스텀 #168

tailwind.config.js
#168
보조 색상으로 사용되는 회색, 빨간 색 색상을 추가해주었음
사용 예시 ) `text-subGray` `border-subRed`
1분!
이미지에 붉은 원으로 표시한 두 가지 색상을 추가함.
=> Feature/커스텀 색상 추가 #168

src/App.tsx, src/components/Layout/Container/FitContainer.tsx, src/components/Layout/Container/FullContainer.tsx, src/components/Layout/Header/Header.tsx, src/components/Layout/Header/index.ts, src/components/Layout/MainLayout.tsx, src/components/Layout/Sidebar/Sidebar.tsx, src/components/Layout/Sidebar/index.ts, src/router/useMainRouter.tsx, tailwind.config.js
- Close #102 
- 레이아웃 구성 및 css를 적용함.
- router 상위에 레이아웃 배치하여, 하위 라우터들을 레이아웃으로 감싸지도록 구현
- 헤더와 사이드바로 구성된 레이아웃과 내부 contents들이 들어가는 컨테이너로 구분하여 구현
- 컨테이너의 경우 메인 페이지와 같이 전체 영역을 쓰는 부분과 게시글 등의 한정된 영역(1080px)에 쓰이는 부분이 나눠짐에 따라 2가지로 구분함.
- 7분
- 상수 부분 따로 빼려고 `tailwind.config.js` 파일에 커스텀하여 사이즈 지정해주었는데 `spacing`만으로 모든 사이즈 지정할 수 없고, `min/max width`의 경우 별도로 커스텀 사이즈 만들어야 돼서 `sidebar`가 두번이나 들어가게 되었네요.. 이대로 가도 괜찮을까요? 아니면 다른 좋은 방법이 있을까요?
```js
spacing: {
header: '66px',
sidebar: '320px',
},
maxWidth: {
container: '1080px',
},
minWidth: {
sidebar: '320px',
},
```
=> Feature/레이아웃 구성 #102

src/components/Table/StandardTable.tsx
- #130
공통 테이블 다크모드 디자인에 맞게 색상 적용하였습니다.
- 테이블 배경색 적용
- row 구분선 색 적용
- 텍스트 색 적용
- 1분
- MUI 컴포넌트인데도 tailwindcss 적용이 되더라구요...! 다만 MUI 내부 css와 충돌되어 적용이 안되는 부분들은 important 처리해주었습니다! 별도로 커스텀할 수 있는 방법이 있긴한데 tailwind로 넣는게 확실히 깔끔하긴 하더라구요! 이렇게 처리해도 괜찮을 지 한 번 봐주세요!
=> Feature/공통 테이블 다크모드 디자인 적용 #130

src/components/Layout/Container/FitContainer.tsx, src/components/Layout/Sidebar/Sidebar.tsx
- #194 
- 헤더와 페이지 제목 사이 간격 컨테이너에 추가
- 헤더가 차지하는 공간 padding으로 넣어두었었는데 공간 컨테이너 외부 영역으로 인식되게 하기 위해 margin으로 변경해주었습니다.
- 컨테이너에서 헤더와 페이지 제목 사이 간격을 padding으로 추가해주었습니다.
2분, 주의깊게 봐야할 부분은 딱히 없습니다!
=> Feature/컨테이너 상단 간격 추가 #194

src/components/Table/StandardTable.tsx
- #130
- key 누락되어 warning 뜨는 거 해결
- API로 테이블 목록 받아오면 row에 `id` 값이 필수적으로 들어온다고 보고
row 타입에 `id` 명시해주고 key 값을 `id`로 지정해주어씃ㅂ니다.
- 2분
=> Feature/테이블 키 누락 워닝 제거 #130

src/components/Button/FilledButton.tsx, src/components/Button/OutlinedButton.tsx, src/components/Button/TextButton.tsx
- Close #200
- 3가지 종류 버튼 공통 컴포넌트 구현
- 디자인 적용
- onClick 이벤트 핸들러 받아올 수 있도록 처리
- disabled 가능하도록 처리
- 5분
- 핸들러 작동, disabled 작동 잘 되는 거 확인하였습니다.
각 버튼 좌측은 활성화 버튼, 우측은 비활성화 버튼입니다.
**preview 예제 코드**
```tsx
import FilledButton from '@components/Button/FilledButton';
import OutlinedButton from '@components/Button/OutlinedButton';
import TextButton from '@components/Button/TextButton';
return (
<div className="space-x-3">
<OutlinedButton onClick={() => console.log('OutlinedButton')}>OutlinedButton</OutlinedButton>
<OutlinedButton disabled>OutlinedButton</OutlinedButton>
<FilledButton onClick={() => console.log('FilledButton')}>FilledButton</FilledButton>
<FilledButton disabled>FilledButton</FilledButton>
<TextButton onClick={() => …
```
=> Feature/버튼 공통 컴포넌트 #200

src/constants/materialTailwindTheme.ts
- #174
- material tailwind `Input` 컴포넌트 디자인 커스텀
- 기본형태 (standard) 지정
- 색 지정
- 3분
```tsx
import { Input } from '@material-tailwind/react';
return (
<Input label="아아" className="w-32" />
);
};
```
- 기본 디자인 입혀져 있는 상태이기 때문에 사용할 때 넓이 조정 제외하고는 크게 css 처리 안 해줘도 될 겁니다!
=> Feature/material tailwind input 커스텀 #174

src/components/Button/FilledButton.tsx, src/components/Button/OutlinedButton.tsx, src/components/Button/TextButton.tsx
- Close #241
- flex 적용된 상위 컴포넌트 높이 따라가지 않도록 내부 요소에 따는 높이 지정
- content 기반으로 높이 지정해주었습니다.
- 0.5분, 변경 사항 간단합니다!
=> Feature/버튼 상위 태그에 따라 높이 변경되지 않도록 처리 #241

src/tailwind.css
- Close #243
-  다크모드를 기본 테마로 하고 있기 때문에 기존 base 컬러인 검은색 대신 흰색이 기본으로 사용되도록 변경
- 0.2분
- tailwind.css 파일에 텍스트 색만 추가하였습니다. 별도의 색 지정 없이 텍스트 흰색으로 잘 나오는 거 확인하였습니다.
=> Feature/기본 텍스트 컬러 흰색 지정 #243

src/components/Pagination/StandardTablePagination.tsx, src/constants/muiTheme.ts
- Close #247
- mui custom color 지정
- 색상들이 헥스코드로 되어 있는 상태인데, tailwindcss 커스텀과 별개로 지정하기 보다는 contants 폴더에 상수로 지정해두고 mui와 tailwindcss에 한 번에 지정해주면 좋을 것 같아서 따로 이슈 생성해서 진행할 예정입니다.
- `primary`는 input, select, datepicker 등에 사용되는 default 색상으로 보면 되고, `secondary`는 pagination 등에 사용되는 색상 배치라고 보면 됩니다. 어떻게 더 확장될 지는 아직 잘 파악이 안돼서 일단 이정도로 작업해두었습니다.
- 기존에 pagination 처리하면서 pagination 색상 배치를 `primary`로 하였는데 input등에 사용되는 컬러가 더 빈번하게 쓰일 것 같아서 pagination color를 `secondary`로 내려주었습니다.
- 1분, 커스텀 하는데 있어서 더 좋은 의견있으면 남겨주세요~!
=> Feature/mui 커스텀 컬러 설정 #247

src/components/Modal/ActionModal.tsx
- #217 #131 
모달창 사용하는 컴포넌트에서 추가하면 됩니다.
``` tsx
const [open, toggleOpen] = useReducer((prev) => !prev, false);
return (
<div>
<FilledButton onClick={toggleOpen}>도서 추가</FilledButton>
<ActionModal
opened={open}
handleOpen={toggleOpen}
title="도서추가"
buttonName="추가"
onActionButonClick={toggleOpen}
>
컨텐츠입니다
</ActionModal>
</div>
);
```
- 기존에는 모달창 컴포넌트안에서 열림여부 state를 관리했는데, 이를 모달창 사용하는 외부에서 관리하도록 수정
- 확인버튼을 누를때 props로 넘겨준 함수(기존) +모달창 닫기함수 추가.
- 모달창 컴포넌트 내부
내부에서 관리하던 state삭제, 외부로 옮김
모달창 닫기함수 추가
- 3분
- 모달창 쓰고싶습니다! 리뷰 부탁드립니다!
=> Feature/모달 열림 여부 props로 전달하도록 확장 #217

src/components/DatePicker/StandardDatePicker.tsx
> - close #213 
datepicker 공통컴포넌트 제작,
spread 연산자 해당파일에만 eslint룰 제거
디자인은 추후에 할 예정
> props로 label, value, setValue 넘김
> 3분
``` tsx
import StandardDatePicker from '@components/DatePicker/StandardDatePicker';
import { DateTime } from 'luxon';
```
``` tsx
const [value, setValue] = React.useState<DateTime | null>(null);
return (
<div>
<StandardDatePicker date={value} setDate={setValue} label="세미나 출석 날짜" />
</div>
);
```
=> Feature/datepicker 공통컴포넌트 제작 #213

src/components/Modal/ActionModal.tsx, src/pages/Study/Modal/StudyModal.tsx
- #286 #287 
- 모달 Material tailwind -> Mui 라이브러리 사용하는 걸로 변경
- mui Dialog 사용하는 걸로 변경하면서 스타일 적용한 부분 해당 라이브러리에 맞춰 새로 적용 및 일부 리팩토링도 같이 해주었습니다.
- width 지정을 통일성있게 가면 좋을 것 같아서 mui에서 제공하는 maxWidth를 각 넓이에 대해 바로 설정해줄 수 있도록 처리해주었습니다.
- @pipisebastian  Dialog 전체적인 padding 같은 경우 디자인 된 사항과 조금 상이한데 라이브러리 자체 기본 padding 쓰는 것도 괜찮을 것 같아서 디자인 쪽 한 번 체크 부탁드립니다!
- 코멘트로 추가 리뷰 요구사항 달아두겠습니다!
넓이 지정 안되어 있는 기본 크기 모달입니다.
넓이를 xs 사이즈로 지정해둔 모달입니다. 아래 예제 코드 참고해주세요.
```tsx
const [libraryAddModalopen, setLibraryAddModalopen] = useState(false);
return (
<div>
<OutlinedButton onClick={() => setLibraryAddModalopen(true)}>추가</OutlinedButton>
<ActionModal
modalWidth="xs"
open={libraryAddModalopen}
onClose={() => setLibraryAddModalopen(false)}
title="도서추가"
actionButtonName="추가"
onActionButonClick={() => { …
```
=> Feature/ActionModal MUI 컴포넌트 사용으로 변경 #287

src/constants/muiTheme.ts
- Close #304
- 프로젝트 폰트로 정한 `IBM Plex Sans KR` 폰트 MUI에 적용되도록 구현하였습니다.
- typography에 폰트 지정해주었고, `Typography`, `Table` 컴포넌트에서 폰트 적용되는 것 확인하였습니다.
- 0.1분
- MUI 컴포넌트인데 폰트 적용 안 되는 부분 있으면 알려주세요!
=> Feature/MUI 폰트 적용

src/components/Progress/StepProgress.tsx, src/pages/SignUp/SignUp.tsx, src/router/useMainRouter.tsx
- Close #292
- 회원가입 진행 카드 레이아웃 UI 구현하였습니다.
- 로고, 외곽 박스, 진행바, 단계 안내 문구, 버튼 UI 구성해주었습니다.
- 진행바의 경우 총 단계 수와, 현재 단계를 props로 넘겨주면 해당 단계에 맞는 진행율을 보여주도록 하는 공통 컴포넌트로 제작하였습니다.
- 7분
- #303 PR이 선행 PR 이라 먼저 리뷰 후 이 PR 리뷰 부탁드립니다.
- [feat : 회원가입 UI 로고 추가](https://github.com/KEEPER31337/Homepage-Front-R2/commit/c271b79d1c14bfed919f7a93da263cdb7e112e48) 이 커밋부터 봐주시면 됩니다.
- `currentStep` 변수에 `1`, `2`, `3` 바꿔가면 넣어보시면 각 단계별로 확인할 수 있습니다.
- 버튼의 3단계 텍스트는 현재 구현되어 있는 `다음`이 아닌 `완료`인데 이건 나중에 기능 추가할 때 처리하겠습니다.
- 중간의 인풋 들어가는 부분의 UI는 다른 PR로 분리해서 올릴 예정입니다.
=> Feature/회원가입 진행 카드 레이아웃 UI 생성 #292

src/components/Table/StandardTable.interface.ts, src/components/Table/StandardTable.tsx
- #299
- checkbox라는 key를 가진 column의 경우 checkbox를 띄워주도록 구현
- column key가 `checkbox`로 넘어올 시 해당 column 테이블 헤더와 각 cell이 체크박스로 구성되도록 구현하였습니다.
- 아직 체크박스 클릭 시 동작 제어 및 헤더 체크박스 클릭 시 전체 체크박스 선택되는 등의 기능은 구현 안 된 상태고, UI상으로 확인할 수 있도록만 구현되어 있습니다.
- 5분
```tsx
import StandardTable from '@components/Table/StandardTable';
import { Column, Row } from '@components/Table/StandardTable.interface';
interface ExampleRow {
no: number;
title: string;
writer: string;
createDate: string;
watching: number;
state: string;
}
const columns: Column<ExampleRow>[] = [
{
key: 'checkbox',
headerName: '선택',
},
{
key: 'no',
headerName: '번호',
},
{ key: 'title', headerName: '제목' },
{ key: 'writer', headerName: '작성자' },
{ key: 'createDate', headerName: '작성일' },
{ key: 'watching', …
```
=> Feature/테이블 체크박스 UI #299

src/components/Modal/ActionModal.tsx
- Close #335
- 아이콘 넣을 수 있도록 `startAdornment`, `endAdornment` prop 추가
- `startAdornment` 있을 시 제목 시작 부분에 추가 가능
- `endAdornment` 있을 시 제목 시작 부분에 추가 가능
- 5분
- [MUI InputAdornment](https://mui.com/material-ui/react-text-field/#input-adornments) 참고하여 작성하였습니다!
```tsx
const [modalOpen, setModalOpen] = useState(false);
return (
<div>
<OutlinedButton onClick={() => setModalOpen(true)}>추가</OutlinedButton>
<ActionModal
modalWidth="xs"
open={modalOpen}
onClose={() => setModalOpen(false)}
title="액션모달"
startAdornment={<VscWarning />}
endAdornment={<VscWarning />}
actionButtonName="액션"
onActionButonClick={() => {
// TODO
}}
>
내용~~
</ActionModal>
</div>
);
};
export default Example;
```
=> ActionModal 모달 제목에 아이콘 추가 가능하도록 확장 #335

src/components/Modal/ActionModal.tsx
- close #327
- 모달창 색 subBlack으로 변경
- 기존 모달창 색이 subBlack이 아니었기에 변경
- 디자인채널 투표대로 brightness 125
- 기존 mui 모달창에 background이미지 때문에 원하는색이 안나왔었기에, 이를 [bg-none](https://tailwindcss.com/docs/background-image)으로 제거
- 0.1분
- PaperProps에 className속성만 보시면 됩니다!
=> Feature/모달창 색 변경 #327

src/components/Selector/Selector.tsx
- #325 
- selector가 label때문에 margin 16px이 존재하는데, label이 없더라도 margin이 유지되어, 이를 제거
- 
변경전, 변경후
=> Feature/label없을시 margin 제거

src/components/Input/BackgroundInput.tsx
- Close #339
- 반투명 포인트 컬러가 배경으로 들어간 인풋 공통 컴포넌트 구현
- 배경색 추가 `bg-pointBlue/5`
- 높이 조정 `h-12`
- 라벨 위치 조정 `top: 8`
- 라벨 위치 조정을 하지 않으면 좌측 이미지 처럼 라벨이 중앙이 아닌 위쪽으로 위치되여 우측 이미지 처럼 변경되도록 조정해주었습니다. [참고](https://stackoverflow.com/questions/53854030/set-textfield-height-material-ui)
- <img width="169" alt="image" src="https://user-images.githubusercontent.com/78250089/232814537-0b4c1cb3-6d69-4043-9410-adb0b8e4c71e.png"> <img width="190" alt="image" src="https://user-images.githubusercontent.com/78250089/232814617-1d1a9b00-0514-4d2a-a1fa-695454c59be4.png">
- 5분
- `StandardInput` 컴포넌트에서 확장된 부분 코멘트로 남겨두겠습니다.
```tsx
<BackgroundInput
value=""
label="ID"
onChange={() => {
// TODO
}}
/>
```
=> Feature/공통 배경 인풋 구현 #339

src/pages/SignUp/SignUp.tsx
- #293
- 인풋 내용 부분 단계별 컴포넌 넣을 수 있도록 호출부 작성
- 단계별 인풋 내용 부분 UI 구현 나눠서 PR 올리기 위해 공통적으로 사용되는 호출부 먼저 PR 올립니다.
- `stepInputSection` 객테의 null 부분에 각 단계 인풋 컴포넌트를 넣으면 단계 안내문구 아래에 인풋 내용 부분 렌더링 되도록 하였습니다.
- 0.1분
=> Feature/회원가입 인풋 호출부 구현 #293

src/pages/senimarAttend/Card/BossCardContent.tsx, src/pages/senimarAttend/Card/MemberCardContent.tsx, src/pages/senimarAttend/Countdown/Countdown.tsx, src/pages/senimarAttend/Selector/SeminarSelector.tsx
#284 #308 #207 #172 
회장과 회원 페이지의 카운트다운 기능을 구현했습니다.
prop로 카운트다운이 시작하는 시간, 끝나는 시간 두 가지를 받습니다.
props로 시작하는 시간을 받아오는 이유는 카운트다운이 출석 시간을 카운트 다운하는 것과 지각 시간 카운트 다운 하는 것 두 가지가 있는데  지각 시간 카운트는 출석 시간 카운트가 끝나기 전까지 (지각 시간 카운트 시작 시간이 되기 전까지) 카운트다운 되지 않고 그대로 있어야 하기 때문입니다.
leftTime과 diff가 따로 존재하는 이유는 카운트다운이 00:00이 되면 '마감'으로 글씨가 바뀌어야 하는데, diff의 타입이 Duration이라 string값을 대입할 수 없고, Duration | string 으로 타입을 바꾸더라도 toFormat을 적용할 수 없어서 그냥 따로 주었습니다.
참고로 아직 api로 적용한 것이 아니라 새로고침을 해도 카운트 다운이 유지되지 않고, 회원 페이지와 회장 페이지의 카운트 다운이 따로놉니다. 이건 api 적용하면 해결될겁니당
> 10분?
=> Feature/세미나 출석 카운트다운 구현 #308

package-lock.json, package.json
close #355
파일 첨부를 위한 react-dropzone 라이브러리를 설치하였습니다.
파일 첨부를 위한 react-dropzone 라이브러리를 설치하였습니다.
1분! 별 거 없습니당
설치한 라이브러리의 요소를 불러왔을 때 제대로 동작하는 것까지 확인했습니다.
| ![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/87e18242-d4a4-47e6-9ff1-53d71563b3d2) | ![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/81465068/f927c46f-0e1d-43f7-bdbf-69ea7bfc208d) |
| --- | --- |
=> Feature/Image 첨부 라이브러리 설치 #355 

.eslintrc.js
close #373
EsLint 전개 연산자 관련 설정 off
eslintrc.js 파일에서 `react/jsx-props-no-spreading` 설정 비활성화
1분! 별 거 없습니다.
=> Feature/EsLint 전개 연산자 관련 설정 off #373

src/constants/muiTheme.ts
- close #343
- mui typography variant 커스텀 구현
- tailwind.config.js랑 똑같이 해줬습니다! 
- 참고) tailwind.config.js
- 추후에 수정하려면 해당 [MUI 링크](https://mui.com/material-ui/customization/typography/#adding-amp-disabling-variants) 참고하시면 됩니다! typescript에서, variant 커스텀 하는 방법 나와있습니다!
- 2분
```tsx
import { Typography } from '@mui/material';
const Intro = () => {
return (
<div>
<Typography variant="h1">h1</Typography>
<Typography variant="h3">h3</Typography>
<Typography variant="paragraph">paragraph</Typography>
<Typography variant="small">small</Typography>
</div>
);
};
export default Intro;
```
=> Feature/mui typography variant 커스텀 구현

src/components/Button/FilledButton.tsx, src/components/Button/OutlinedButton.tsx, src/components/Button/TextButton.tsx
- close #358
- material tailwind -> mui로 변경해줬습니다
- css) `font-base`뺀거는, 어차피 mui에서 폰트 설정 알아서 해주기 때문에, tailwind에서 따로 넣어줄 필요x
- css) 원래보다 살짝 작아질텐데, 그게 글자 크기를 10.5px -> 10px로 바꿨기 때문입니다! 일단은 `!text-small`로, tailwind상에서 10px로 박아놨습니다! (**`text-[10.5px]`적용하면 원래랑 똑같이 나옵니다!**)
- css) `leading 4`는 원래 버튼이 line height가 1rem이어서, 통일해주려고 넣었습니다!
- 추후에 버튼 font 크기 10px / 14px 선택 가능하도록 기능 추가해야 합니다!
- 1분
=> Feature/버튼 material tailwind 모듈 mui로 변경 #358

src/components/Button/OutlinedButton.tsx
- close #359 
- https://github.com/KEEPER31337/Homepage-Front-R2/pull/360 해당 풀리퀘부터 보고 와주시면 감사하겠습니다!
- outlinedButton부분에서 startIcon, endIcon만 보시면 됩니다!
- outlinedButton에 아이콘 추가기능 넣었습니다
- start Icon, end icon은 [mui button컴포넌트](https://mui.com/material-ui/react-button/#buttons-with-icons-and-label) 부분 참고해주세요!
- 
- 1분
```tsx
import { VscAdd } from 'react-icons/vsc';
import OutlinedButton from '@components/Button/OutlinedButton';
<OutlinedButton
startIcon={<VscAdd style={{ width: '15px', height: '15px' }} />}
endIcon={<VscAdd style={{ width: '15px', height: '15px' }} />}
>
도서 추가
</OutlinedButton>
```
=> Feature/outlined button 아이콘 추가 기능 #359

src/components/Input/BackgroundInput.tsx, src/pages/SignUp/Section/SignUpFirstInputSection.tsx, src/pages/SignUp/SignUp.recoil.ts, src/pages/SignUp/SignUp.tsx
- #295 
회원가입 1단계
- 아이디
- 비밀번호
- 비밀번호 확인
에 프론트에서 처리해줄 수 있는 기능 구현하였습니다.
추가로 작업해야 하는 기능
- 아이디 중복 체크 기능 (API 사용)
- 비밀번호 변경 시 비밀번호 확인 에러 상태 해당 필드 blur하지 않아도 바로 반영되도록 처리
- 테스트 코드 짜기
- ~~#378 선행 PR 먼저 리뷰 부탁드립니다!~~ (머지 완료!)
- 예상 소요 시간 `20분` (라이브러리 숙련 정도에 따라 리뷰 시간 상이할 듯 합니다!)
- 디자인 관련해서는별도 PR에서 처리해줄 예정이니 이 PR에서는 디자인 관련 리뷰 패스하셔도 됩니다!
(인풋 배경색이 디자인과 다르다거나 하는 등등 있을 겁니다!)
- `react-hook-form`, `recoil` 사용한 부분 익숙치 않아서 중점적으로 리뷰 부탁드립니다!
- `Controller` 사용한 부분이라거나 중복적인 부분 리팩토링 할 부분 기능 구현 완료 후 싹 한 번 검토해볼 예정이긴 합니다만 좋은 의견 있다면 여기서도 많은 피드백 부탁드립니다!
=> Feature/회원가입 1단계 기능 구현 #295

src/constants/muiTheme.ts, tailwind.config.js
- close #389
- 기본 폰트 크기 paragraph 16 -> 14px로 변경 (mui, tailiwind 둘 다)
- 30 초
=> Featrue/기본 폰트 크기 16 - 14px로 변경

src/components/Button/FilledButton.tsx, src/components/Button/OutlinedButton.tsx, src/components/Button/TextButton.tsx
- close #396
- line height을 고정시켰는데, 폰트 사이즈 14px의 경우 고정된 길이때문에 윗부분이 조금 짤려서 이를 해결함.
- 30초
=> Feature/버튼 line heigth 제거

src/api/dto.ts, src/api/signUpApi.ts
- Close #385
회원가입할 때 필요한 API 틀 작성하였습니다.
- `reactQuery` + `axios` 사용하여 API 받아올 수 있도록 구현하였습니다.
- 회원가입할 때 필요한 아래 API들 받아오도록 해주었습니다.
- 회원가입
- 이메일 인증
- 아이디 중복 체크
- 이메일 중복 체크
- 학번 중복 체크
- 10분 소요 예상
- query key 사용하는 부분 배열에 공통되는 부분과 차이 나는 부분 구별해서 지정해주었는데 괜찮은 지 리뷰 부탁드립니다!
```tsx
import {
useSignUpMutation,
useEmailAuthMutation,
useCheckLoginIdDuplicationQuery,
useCheckEmailDuplicationQuery,
useCheckStudentIdDuplicationQuery,
} from '@api/signUpApi';
...
const signUpPageValue = useRecoilValue(signUpPageState);
const { mutate: createAuthMutation } = useSignUpMutation();
const { mutate: emailAuthMutation } = useEmailAuthMutation();
const { data: isUniqueLoginId } = useCheckLoginIdDuplicationQuery({ loginId: signUpPageValue.loginId });
const { data: isUniqueEmail } = …
```
=> Feature/회원가입 API 틀 생성 #385

src/components/Layout/Header/Header.tsx
- Close #269
- 헤더에 로그인 페이지로 갈 수 있는 버튼 추가하였습니다.
- 로그인 후 프로필 아이콘에 유저 프로필 띄워줄 거라 userInfo가 없을 때 로그인 버튼을 띄워주는 식으로 구현하였습니다.
- 버튼 클릭시 로그인 페이지로 이동하는 기능도 작동 확인하였습니다.
- 예상 소요시간 5분
=> Feature/헤더 로그인 전 로그인 버튼 띄워주기 #269

src/components/Navigation/SubCategoryNav.tsx, src/constants/category.ts
- Close #271
- 사이드바 항목 클릭하면 카테고리 path로 지정된 경로로 이동되도록 처리하였습니다.
- router에 넣지 않은 경로들은 임시로 `#`으로 경로 지정해주었고, router에 들어간 경로는 바로 적어주었습니다.
- 클릭시 경로 이동되는 것 확인하였습니다.
- 현재는 useMainRouter에 라우터로 넣어주는 것과 별도로 category에 경로 추가해줘야 이동이 되는데 나중에 한 번에 처리되도록 확장시킬 예정입니다. #406
- 예상 소요 시간 `3분`
=> Feature/사이드바 라우터 연결 #271

src/components/Navigation/CategoryNav.tsx, src/components/Navigation/SubCategoryNav.tsx
- #272 
- 사이드바 상위 카테고리 클릭시 열림 여부에 따라 background 색 처리되도록 하였고, 현재 경로 카테고리의 경우 text 색 처리 해주었습니다.
- `selected`된 카테고리 항목에는 자동으로 하이라이트 처리되고, 현재 경로와의 비교는 `react-router-dom`에서 제공하는 `useLocation`을 통해 현재 경로를 받아와서 `matchPath` 함수를 통해 같은 경로인 지 비교해주었습니다.
- 상위 카테고리 새로 고침 시 현재 경로 카테고리를 포함한 카테고리가 기본적으로 열리면 좋을 것 같은데 현재 PR에서는 적용 안 된 상태입니다. 상위 카테고리에 대한 경로를 추가하여(다른 좋은 방법있으면 의견 부탁드립니다!)  작업하는 것 이슈 새로 파서 반영해보겠습니다. #408
- 선행 PR입니다. #407 PR 먼저 리뷰 부탁드립니다!
- 이 PR은 [feat : 카테고리 열렸을 때 색 들어가도록 선택 여부 지정](https://github.com/KEEPER31337/Homepage-Front-R2/commit/c34913a87238243246c013b40282a558aa19c0ed) 커밋 부터 확인하면 됩니다!
- 예상 소요 시간 `7분`
=> Feature/사이드바 현재 페이지 하이라이팅 #272

src/pages/Game/Game.tsx, src/router/useMainRouter.tsx
- Close #401
- 게임 페이지 탭, 게임 규칙 버튼, 포인트 정보 부분 UI 구성하였습니다.
- 게임 페이지 라우터에 추가해주었습니다.
- point의 경우 추후 API 받아와서 띄워줄 예정이라 현재는 임시 숫자로 넣어주었습니다.
- 실제 게임화면의 경우 별도 프로젝트에서 들고와 띄워줄 거라서 해당 PR에는 화면이 포함되어 있지 않습니다.
- 예상 리뷰 소요 시간 7분
=> Feature/게임페이지 UI 구현 #401

src/components/Button/FilledButton.tsx, src/components/Button/OutlinedButton.tsx, src/components/Button/TextButton.tsx
- close #397
- 선행 풀리퀘 #398입니당
- outlineButton disable시 border색 pointColor 적용되는거 제거했씁니다
- 일단 outlineButton에 border색만 바꿨는데, 다른 버튼의 disable은 mui 기본 디자인거 그대로 입니다! 
이대로 나쁘지 않을 것 같아서 다 냅뒀습니다!
2023.06.30) 추가 -> props diabled로 판별하는게 아닌, tailwind css상에서 disabled속성으로 바꿨습니다!
그리고 원래는 outlinedButton만 색 바꿔줬는데, text, filled 다 subGray색으로 변경했습니다! 아래가 바뀐 버튼입니다
=> Feature/버튼 disable시 border색 변경 #397

src/components/Modal/MailAuthenticationModal.tsx
- Close #434
- `다른 이메일로 인증` 버튼 클릭 이벤트 props로 받아오도록 처리
- `인증 메일 재발송` 버튼 클릭 이벤트 props로 받아오도록 처리
- 회원가입과 로그인에 공통적으로 사용되는 인증 메일 모달의 각 버튼을 사용되는 곳에서 서로 다르게 처리할 수 있도록 props로 이벤트 핸들러 받아올 수 있도록 해주었습니다.
- 예상 소요 시간 `1분`
- 네이밍 괜찮은 지 한 번 봐주세요!
=> Feature/인증 메일 모달 버튼 클릭 이벤트 핸들러 props로 받아오기 #434

src/api/dto.ts, src/pages/BoardWrite/BoardWrite.tsx, src/pages/BoardWrite/Modal/SettingUploadModal.tsx
- Close #469
- 게시글 작성 페이지 설정 및 업로드 모달 체크 박스 이벤트 핸들러로 처리해주었습니다.
- 게시글 생성 api 호출은 상위 컴포넌트에서 처리할 거라 props로 `postSettingInfo`, `setPostSettingInfo` 받아와서 처리해주었습니다.
- `postSettingInfo` 타입 `null`도 가능하도록 해주었는데 api에서 null로 보내주면 default 값으로 설정해줘서 따로 체크박스 건드리지 않으면 `null` 상태로 보내도 괜찮을 테니 이렇게 처리해주었습니다.
- 각 체크박스는 하나의 핸들러로 다룰 수 있도록 해주었습니다.
- 예상 소요 시간 `3분`
=> Feature/게시글 설정 및 업로드 모달 기능 #469

src/api/dto.ts, src/components/Viewer/StandardViewer.tsx, src/mocks/postApi.ts, src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Section/BannerSection.tsx, src/pages/board/BoardView/Section/PostSection.tsx
- Close #439 
- 게시글 조회 게시글 내용 UI 구성
- Banner 섹션 - 썸네일이 배너로 들어가고, 게시글 정보 및 글 수정/삭제 버튼 있는 섹션
- Post 섹션 - 게시글 내용, 파일, 추천/비추천 버튼 있는 섹션
- 예상 소요시간 `5분`
- 급하게 하느라 중간중간에 변수로 안 두고 임시로 하드 코딩 해둔 텍스트들 몇몇 있는데 기능 구현하면서 처리해보겠습니다!
- 배너섹션 작성자, 작성시간, 조회수 부분도 기능 구현하면서 UI 좀 더 다듬어 올리겠습니다!
=> Feature/게시글 조회 게시글 내용 UI #439

src/api/dto.ts, src/api/postApi.ts, src/pages/BoardWrite/BoardWrite.tsx, src/pages/BoardWrite/Modal/SettingUploadModal.tsx, src/pages/board/BoardList.tsx
- Close #431 
- 게시글 작성 api 연동하였습니다.
- 게시글 작성 api request로 보낼 값들 입력값 반영되도록 기능 추가하였습니다.
- 썸네일과 파일의 제외한 게시글 작성 정보들 api 연동하여 구현하였습니다. (썸네일, 파일도 빠른 시일 내에 처리해올리겠습니다.)
- api 요청 형식에 맞게 `request` 객체 자체는 `application/json` 타입으로 지정해서 `formData`에 넣어주고, `formData` 자체는 `multipart/form-data` 처리해서 api 보내주는 식으로 구현하였습니다. (@pipisebastian 도서 관리 페이지 api도 동일한 구성으로 알고 있는데 참고해주세요!)
- 게시판 글쓰기 버튼 클릭 -> 게시글 작성 -> 업로드 -> 게시판으로 이동 flow 가능하도록 처리된 상태입니다.
- 게시판 카테고리는 아직 적용이 안 된 상태여서 자유게시판, 익명게시판 등의 카테고리 다루는 부분은 포함되지 않은 상태입니다. 나중에 게시판 구현할 때 같이 처리해보겠습니다.
- 10분
=> Feature/게시글 작성 api 연동 #431

src/api/commentApi.ts, src/api/dto.ts, src/api/postApi.ts, src/components/Image/ServerImg.tsx, src/mocks/postApi.ts, src/pages/BoardWrite/BoardWrite.tsx, src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Card/CommentCard.tsx, src/pages/board/BoardView/Card/CommentCardFooter.tsx, src/pages/board/BoardView/Card/CommentCardHeader.tsx, src/pages/board/BoardView/Section/AdjacentPostNavSection.tsx, src/pages/board/BoardView/Section/BannerSection.tsx, src/pages/board/BoardView/Section/CommentSection.tsx, src/pages/board/BoardView/Section/PostSection.tsx
- Close #492 
- 배너, 게시글 내용, 댓글 섹션에 필요한 api 연동 해주었습니다.
- 댓글 섹션은 조회 api만 적용해둔 상태이고 댓글/대댓글 생성, 수정, 삭제 및 좋아요/싫어요 처리 관련해서는 별도의 이슈(#494)에서 진행 예정입니다.
- 각 api 연동 및 연동 후 수정 필요한 부분 수정해주었습니다.
- 서버에서 받아오는 이미지 처리를 위해 공통컴포넌트로 만들어주었습니다!
서버에서 정상적으로 이미지 받아오는 경우와 정상적으로 이미지 받아오지 않는 경우에 대해서 처리하도록 구현하였습니다.
- 서버 이미지는 상대경로로 제공되기 때문에 props로 `src` 넘겨주면 `src` 앞에 서버 주소를 붙여주도록 해주었습니다.
- 이미지를 정상적으로 받아오지 못할 경우 썸네일 기본 이미지인 로고 이미지를 띄워주도록 해주었습니다.
- 정상적으로 이미지 받아올 경우, 받아오지 못할 경우 스타일을 다르게 적용할 수 있기 때문에 각각 `className`과 `errorClassName`을 props로 받아올 수 있도록 해주었습니다!
- ~~#491 선행 PR 먼저 리뷰 부탁드립니다!~~ 머지 완료
- 이 PR은 [feat: 이전글, 다음글 받아온 api 적용](https://github.com/KEEPER31337/Homepage-Front-R2/commit/3a54bbb91ffc37710e3b9f17b44684c4b3efd7ae) 부터 보시면 됩니다!
=> Feature/게시글 조회 api 연동 #492

src/components/Pagination/StandardTablePagination.interface.ts, src/components/Pagination/StandardTablePagination.tsx, src/components/Table/StandardTable.tsx, src/hooks/useGetPage.ts
- Close #499 
- #130 
- 페이지네이션으로 테이블 목록 제어할 수 있도록 확장해주었습니다.
- 페이지네이션에서 page를 url searchParam으로 부여하도록 처리하였습니다.
- 페이지에 따른 목록을 불러올 때 searchParam으로 page를 불러와 사용하면 되는데 UI 상에서 띄워주는 page는 1부터 시작이고, api에서 받는 page는 0부터 시작이기 때문에 searchParam을 불러오는 부분과 page api 형식에 맞게 변환하는 부분을 합쳐 `useGetPage`라는 커스텀 훅을 제작하였습니다.
- 사용되는 부분 예시입니다. 예시로 간략하게 보여주기 위한 거라 코드가 좀 이상할 수 있는데 `useGetPage`로 page 불러와 api 파라미터로 넘겨줄 수 있다는 것과, `paginationOption`으로 페이지네이션 관련 정보 넣어줄 수 있다는 것만 확인해주세요!
```tsx
const BoardList = () => {
const { page } = useGetPage();
const { data: posts } = useGetPostListQuery({ categoryId: 104, page });
if (!posts) {
return null;
}
return (
<StandardTable
columns={boardColumn}
rows={posts.content.map((post) => ({ no: post.id, ...post }))}
paginationOption={{ rowsPerPage: posts.size, totalItems: …
```
=> Feature/StandardTablePagination 외부 props 받아와 제어 #499

package-lock.json, package.json
#462 #522 
corss-env 모듈 설치로 모든 os에서의 실행 스크립트를 통일해주었습니다.
> cross-env 모듈은 프로젝트 참여자 각각이 MacOS, Windows, Linux 등 다양한 OS 마다 환경변수를 설정하는 방법이 다르기 때문에 이것에 대한 대책을 마련한 모듈이다. 그래서 corss-env 패키지를 사용하면 동적으로 process.env(환경 변수)를 변경할 수 있으며 모든 운영체제에서 동일한 방법으로 환경 변수를 변경할 수 있게 된다.
[참고](https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-cross-env-%EB%AA%A8%EB%93%88-%EC%82%AC%EC%9A%A9%EB%B2%95)
실행 스크립트 내 `GENERATE_SOURCEMAP=false craco start `추가로(https://github.com/KEEPER31337/Homepage-Front-R2/issues/462) 윈도우 os에서는 start 스크립트가 실행되지 않는 오류가 있었습니다. 
기존에는 window용 실행 스크립트(winStart 같이..)를 따로 만들어 추가할 생각이었지만 그러면 윈도우에서 코드를 실행시킬때` npm run winStart`처럼 작성해야하는 번거로움이 있었고, winStart처럼 스크립트를 분리시키는 것보다 cross-env로 통일시키는 게 나을 거 같아 cross-env를 적용시켰습니다
이거 하나 하자고 모듈을 하나 다운받아야 해서 그게 좀 그렇긴 한데...^^;
1. 그냥 `GENERATE_SOURCEMAP=false craco …
=> Feature/실행 스크립트에 cross-env 추가 #522

src/api/authApi.ts, src/api/dto.ts, src/api/logInApi.ts, src/components/Layout/Header/Header.tsx, src/components/Layout/Header/Menu/AccountMenu.tsx, src/hooks/useCheckAuth.ts, src/pages/login/Login.tsx, src/recoil/member.recoil.ts
- Close #530
- 로그인 시 필요한 정보 localstorage에 저장하고 로그인 여부에 따른 헤더 처리해주고 로그아웃 기능 추가하였습니다.
- 로그인 성공 시 member atom 값 설정해주는 로직 UI와는 상관없는 부분이라 로그인 컴포넌트 쪽에서 API 쪽으로 옮겼습니다.
- 로그아웃 시 member atom 값 비우고 메인페이지로 이동하도록 처리해주었습니다.
- 예상 소요 시간 `7분`
- 프로필 이미지 해당 user에 맞게 띄워주는 거 추가로 처리해야 합니다. 이슈 분리하여 진행 예정입니다 #531 
- ~프로필 이미지 클릭 시 뜨는 계정 정보 이메일이 아닌 아이디로 처리하고 싶은데 로그인 응답으로 아이디는 제공해주지 않아서 백엔드 측과 의논해볼 예정입니다.~ 아이디 받아와 띄워주는 걸로 변경 완료!
=> Feature/로그인 시 계정 정보 저장 및 헤더 반영 #530

src/api/dto.ts, src/api/libraryManageApi.ts, src/pages/admin/LibraryManage/Modal/OverdueBookModal.tsx, src/pages/admin/LibraryManage/Tab/BorrowingStatusTab.tsx, src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
- #570  #573 선행리뷰 부탁드립니다~
- 선행리뷰 머지되면, 코드에 코멘트 달아서 설명하겠습니다
- 연체도서 목록 받아와서 띄워줬습니다!
- 대출현황 탭에 테이블 목록 api는 지금 만드는 중이라, 연체도서부터 했습니다!
> 5분
=> Feature/대출 현황 탭 연체도서 목록 받아오기 #574

package-lock.json, package.json, src/api/dto.ts, src/api/postApi.ts, src/components/Layout/MainLayout.tsx, src/pages/board/BoardList/BoardList.tsx, src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Modal/SecretPostModal.tsx, src/pages/board/BoardWrite/Modal/SettingUploadModal.tsx
- #135 #261 
- 비밀글 관련 처리과 테이블에 빠진 요소 추가 해주었습니다.
- 비밀글 모달 원래 기획상으론 게시판에서 목록 클릭 시 모달 뜨는 방식인데, API 상으로 비밀번호 확인하는 게 단일 게시글 조회 API 호출 시에 확인이 이루어지는데 게시판에서 해당 API를 확인 용도로 호출하기도 그렇고, 비밀번호 확인용의 API 요청할까 싶기도 했는데 url로 게시글 들어오는 경우에는 비밀번호 입력이 불가할 것 같아서 게시글 조회 쪽에서 처리해주었습니다.
- 비밀글 모달 취소하면 다시 게시판으로 돌아가도록 처리해주었습니다.
- 비밀번호 다를 시에 에러 띄우는 게 까다로운 것 같아서 일단 react-hot-toast 활용하여 toast 메시지로 뜨도록 처리해두었습니다. 일단 다른 급한 작업들 부터 우선적으로 처리하고 와서 더 좋은 방법 있는 지 살펴보겠습니다.
- `7분`
- 아직 게시판 남은 작업 더 있는데 다른 부분 작업하고 돌아올 예정이라 끊어서 PR 올립니다.
=> Feature/게시판 남은 작업 처리

src/api/dto.ts, src/components/Uploader/ImageUploader.tsx
- Close #587
- 썸네일 수정 상태일 때 썸네일 경로 전달 시 해당 썸네일 이미지 띄워주도록 처리하였습니다.
- 2분
```tsx
<ImageUploader
isEdit={Boolean(editMode)} // true
thumbnailPath={editMode?.post.thumbnailPath}
setThumbnail={setThumbnail}
/>
```
=> Feature/이미지 업로더 사진 받아오기 #587

src/components/Table/StandardTable.tsx
- #130
-  row가 많아졌을 때라거나 테이블 높이가 너무 공간을 많이 차지하는 것 같아서 테이블 높이 조정할 수 있도록 props 추가하고 기본 size small로 처리해주었습니다. 기존 테이블 사이즈 사용하려면 medium 사용하면 됩니다.
- 1분
before
after
=> Feature/테이블 높이 줄이기 #130

src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Section/CommentSection.tsx, src/pages/board/BoardWrite/BoardWrite.tsx
- Close #595 
- 익명 게시판의 경우 임시저장 못하도록 처리하고, 게시글 수정/삭제, 임시저장, 댓글 삭제 불가하다는 문구 추가해주었습니다.
- 5분
- 문구 배치라거나 색 괜찮나욤?~?
=> Feature/익명 게시판 임시저장 안 되도록 처리 및 안내 문구 띄우기 #595

src/App.tsx, src/api/postApi.ts, src/pages/board/BoardView/BoardView.tsx
- Close #578 
- Close #568
- 게시판으로 부터의 접근이 아닌 url로 접근 혹은 이전글/다음글로 접근의 경우 api 호출 이후 비밀글인 지 판별이 가능하여 api 에러에 따른 비밀글 처리해주었습니다.
- 에러 발생 시 바로 비밀번호 입력 모달 띄우기 위해 react-query 기본 옵션으로 retry 꺼주었습니다. (401에러 발생시 로그인 페이지로 이동 느리게 반응하는 것도 해당 작업으로 즉각적인 반응 가능하게 되었습니다.)
- 예상 소요 시간 `5분`
=> Feature/비밀글 url로 접근 시 처리 #578

src/pages/admin/LibraryManage/Tab/RequestManageTab.tsx
- Close #603 
- 승인요청 페이지에 **대출 신청, 반납 신청** 정보만 받아와줘야하는데, 대출 승인, 대출 거부 등 모든 정보가 받아와짐
- 이에 대출 신청, 반납 신청 정보만 받아오도록
**- 0.1분**. 처음엔 다른문제인줄 알고 삽질하다가.. api문서를 읽고 바로 해결했습니다..ㅎㅎ..
대출관련정보가 문서에 나와있는 requests, willreturn, requests_or_willreturn, overdue 4가지를 다 말하는 줄 알았는데,
대출반려, 대출중 등 모든 정보가 들어가더군요,,! 
이전
이후
=> feat : 승인요청 페이지 대출,반납 정보만 받아와지도록

src/api/dto.ts, src/api/postApi.ts, src/components/Uploader/FileUploadList.tsx, src/components/Uploader/FileUploader.tsx, src/pages/board/BoardView/Section/PostSection.tsx, src/pages/board/BoardWrite/BoardWrite.tsx
- Close #597
- 게시글 파일 수정 기능 구현하였습니다. 
- 파일 관리하는 배열에 크게 3가지가 있는데, `추가할 파일`, `이미 있던 파일`, `삭제할 파일`로 관리가 됩니다. API에서 수정 시에 단일 처리가 아닌 추가/삭제 API로 분리되어 있으며 최종적으로 수정 버튼 클릭 시 한 번에 반영되야 하기 때문에 이렇게 각각의 배열로 두는 방식으로 확장을 해주었습니다.
- `추가할 파일`은 기본적으로 사용하는 배열으로 최종적으로 추가될 파일 배열이며 수정 시에 추가할 파일도 해당 배열에서 관리됩니다.
- `이미 있던 파일`은 수정 시에 사용한다고 보면 되는데, 서버에 올라가 있는 파일을 받아와 띄워주기 위함입니다. 조회 용도로만 쓰입니다.
- `삭제할 파일`은 파일 id로 삭제가 이루어 지고 서버에 올라이 있는 파일 대상으로 삭제할 파일 id를 담는 배열입니다.
아래 코멘트로 props별로 설명 추가로 남겨두겠습니다.
- 리뷰 예상 시간 10분
=> Feature/게시글 파일 수정 #597

src/components/Card/FixedPostingCard.tsx, src/components/Card/PostingCard.interface.ts, src/components/Card/PostingCard.tsx, src/components/Table/GridTable.tsx, src/pages/board/BoardList/BoardList.tsx
- #135, Close #261, Close #556
- 그리드 뷰에 처리 안 되어 있던 작업들 해주었습니다.
- 추가된 기획 사항으로 추천수 추가해주었습니다.
- 비밀글의 경우 이미지에 자물쇠 이미지와, 제목 `비밀글입니다.` 로 처리해주었습니다.
- 클릭 시 게시글로 이동하도록 처리해주었습니다.
- 공지글 상단에 따로 빼주었고, 공지글이 있는 경우만 공지글 섹션이 뜨도록 처리해주었습니다.
- 예상 소요 시간 15분
- 디자인 했던 것에서 덜 구현된 부분이 있는데 일단 기능 돌아가는 게 급한 것 같아서 개발 공수가 덜 드는 방향으로 디자인 적용해두었습니다! 디자인 맞춰 더 다듬는 건 추후 과제로 미뤄둘 예정입니다!
=> Feature/게시판 그리드뷰 다듬기

src/components/Image/ServerImg.tsx
- #509
- null 이미지일 때 api 호출 자체를 안 하도록 처리하였습니다.
- null 일 때 로고 이미지는 정상적으로 출력하고 있으나, 콘솔에 에러 문구 뜨는 게 거슬려서 null일 때 호출 안 하도록 조건부로 처리해주었습니다.
- 1분
- null이 아니라 서버 경로 오류로 대체 텍스트 뜨는 것도 대체 이미지(로고)로 뜨도록 처리할 예정인데 #619 에서 처리 예정입니다!
=> Feature/ServerImg null 일때 api 호출로 인한 콘솔 에러 제거 #509

src/pages/board/BoardView/Card/CommentCard.tsx
- Close #608
- 삭제된 댓글에 대댓글 없을 경우 헤더만 남도록 처리하였습니다. (Preview 이미지 참고)
- 1분
|Before|After|
|------|------|
|<img width="1109" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/d7c6cd24-3849-4dfd-b163-7386e80ccd2c">|<img width="1109" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/3a2dcbb1-34d2-406c-83cc-9f9d64c5807d">
|
=> Feature/삭제된 댓글 아래 여백 없도록 처리 #608

src/components/DatePicker/StandardDatePicker.tsx, src/pages/SignUp/Section/SignUpSecondInputSection.tsx
- #296. Close #388
- 회원가입 페이지에 사용될 배경색 datepicker를 위해 StandardDatepicker 확장해주고, UI도 조금 다듬어주었습니다.
- 예상 소요 시간 5분
- Datepicker `renderInput`으로 `StandardInput` 넣고 싶었는데 `value` 타입이 `string`이어야 하는데 `unknown` 보냈다는 타입 에러가 나서 `String(params.value`)로 형변환도 해보고 `params.value as string`으로 타입 강제도 해보았는데 계속 `unknown`이라 뜨더라구요! 그래서 일단 `TextField` 컴포넌트 사용했습니다! 관련해서 해결 방법 알고 있으신 분 있으면 코멘트 부탁드립니다!
`hasBackground === false`
|UI 개선 전|UI 개선 후|
|------|------|
|<img width="367" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/f10d6bac-8b44-4cdb-a884-60b75f35ce70">|<img width="368" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/e16f5620-4d54-40d1-8ebb-b07c520779ed">|
`hasBackground === true`
=> feat : StandardDatePicker 배경색 확장 및 UI 개선

src/components/Layout/Header/Menu/AccountMenu.tsx
- Close #632
- useNavigate 사용하여 헤더 메뉴 프로필 버튼 클릭 시 페이지 이동 되도록 처리하였습니다.
- 예상 소요 시간 1분
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/0c209395-21cf-4c67-9d98-90274af4d826
=> Feature/헤더 메뉴에 프로필 경로 이동 기능 구현 #632

src/components/Layout/Header/Menu/AccountMenu.tsx
- Close #544, Close #633
- 위의 이미지 같이 헤더 메뉴를 통한 로그아웃 -> 로그인 -> 메인페이지로 이동 할때 좌측 상단에 메뉴창이 뜨면서 anchorEl 관련 에러가 발생하는 이슈가 있었습니다.
- anchorEl가 참조하는 요소를 이동하면서 찾지못해 발생한 에러로 보여져서 헤더 메뉴를 통한 이동 시 메뉴가 닫히도록 처리하여 anchorEl 참조를 끊어줄 수 있도록 처리해주었습니다.
- 1분
=> fix : 메뉴를 통한 경로 이동 시에 에러 발생하지 않도록 메뉴창 닫아주도록 처리

src/constants/muiTheme.ts
- Close #648
- 인풋 자동 완성 시 배경색 안 들어가도록 처리하였습니다. 브라우저 별로는 테스트 못해봤는데 크롬에서는 잘 동작합니다. 다른 브라우저에서 잘 적용 안 될 경우 고려하여 다크 테마일 때의 배경색도 같이 처리해주었습니다.
- 1분
이전 상태
->
다크 테마 적용
->
현재 상태
=> Feature/인풋 자동 완성 시 배경색 안 들어가도록 처리 #648

src/api/signUpApi.ts, src/components/Input/EmailAuthInput.tsx, src/pages/SignUp/Section/SignUpFirstInputSection.tsx, src/pages/SignUp/Section/SignUpSecondInputSection.tsx, src/pages/SignUp/Section/SignUpThirdInputSection.tsx
- Close #295 
- Close #296
- 학번 중복 체크, 아이디 중복 체크 적용하였습니다.
- 중복 확인 버튼 클릭 시
- 중복된 학번/아이디면 인풋에 에러 문구 띄워주고
- 중복되지 않은 경우 체크 아이콘으로 변경되도록 처리
- 체크 아이콘으로 변경 후 학번/아이디 변경 시 다시 중복 확인 전 상태로 리셋
등 처리해주었습니다.
- 예상 소요 시간 15분
- 에러 발생 후 인풋 변경 시 바로 에러 제거되는 게 아닌 `onBlur` 시 제거 됩니다. 게시글 작성 쪽도 마찬가지인데 추후 한꺼번에 처리해보겠습니다!
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/5d1a5d85-45e8-47a4-80df-6af6d0e7236d
=> Feature/회원가입 남은 작업 처리 - 중복 체크 관련

src/components/Input/AutoComplete.tsx, src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx, src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
#615 
AutoComplete 공통컴포넌트 수정했습니다.
- Item 대신 AutoCompleteItem으로 변경했습니다
- SingleAutoCompleteValue, MultiAutoCompleteValue 타입을 export 해서 useState에 넣을수 있도록 했습니다
- 제네릭 타입을 사용해서 multiple 여부에 따라 value의 타입이 바뀌도록 했습니다. 이제 value를 as 로 타입변경 할 필요가 없어졌습니다
- 라벨 중복시 key가 겹치는 현상을 수정했습니다. key 값을 label_value로 바꿨습니다. label과 value 모두 같은 경우는 AutoComplete에 둘다 동시에 들어가면 안된다고 생각하여 key 겹치는걸 고려하지 않았습니다
- multiple 일때 처음엔 fixed 값이 뜨지않는 문제를 수정했습니다
> 5분
타입문제를 위주로 작업하였습니다. 실제로 적용했을때 타입 문제가 있거나 관련해서 좋은 아이디어 있으면 알려주세요
=> Feature/AutoComplete 컴포넌트 개선 #615

src/api/dto.ts, src/api/memberApi.ts, src/pages/Profile/Profile.tsx, src/pages/Profile/Section/ProfileSection.tsx, src/pages/Profile/Tab/ProfileTab.tsx
- #661
- 프로필 섹션 ui 구성 및 회원정보 연결
- ui 대충 틀만 구현해서, 14.0기 같은 세세한건 냅뒀습니다!
- 아 혹시 기본 프로필은 어디서 가져오면 될까요??
=> fest : 프로필 섹션 ui 구성 및 회원정보 연결

src/components/Pagination/StandardTablePagination.interface.ts, src/components/Pagination/StandardTablePagination.tsx, src/hooks/usePagination.ts
- Close #658, Close #647
- 한 페이지에 여러 테이블 사용 시에도 페이지네이션 원활하게 사용할 수 있도록 pageKey 받도록 확장해주었습니다.
- 테이블 페이지네이션과 usePagination 훅 개별적으로 page searchParam 다루도록 처리해주었는데 서로 연계되는 로직이어서 테이블 페이지네이션 내부에서도 usePagination 훅을 사용한 로직으로 변경해주었습니다.
- pageKey 넘겨주지 않으면 기존과 똑같이 page라는 이름의 key로 적용됩니다.
- 10분
- 처리 방식 괜찮은 지 체크 부탁드립니다!
=> Feature/page param key 받아서 처리 가능하도록 확장 #658

src/api/dto.ts, src/api/postApi.ts, src/pages/Profile/Tab/BoardTab.tsx, src/pages/Profile/Tab/BoardTable/MyBoardTable.tsx, src/pages/Profile/Tab/BoardTable/TempBoardTable.tsx
#642 
임시 작성글과 작성글 탭입니다
각각 컴포넌트로 넣어줬습니다.
usePagenation이 겹쳐 페이지가 같이 넘어가는 문제가 있습니다. 옆에 포인트내역도 같이 넘어갑니다...
클릭시 board/view/{boardId}로 넘어가도록 했습니다
개발자모드를 켠 상태에서 보드로 갔다가 뒤로가기를 하면 에러창이 뜹니다. 개발자모드를 안키면 안뜨고 그냥 무시해도 동작에 문제가 없긴합니다...
5분
페이지 이동경로 맞는지 확인부탁드립니다.
=> Feature/프로필 작성글탭 #642

src/api/dto.ts, src/api/dutyManageApi.ts, src/api/memberApi.ts, src/components/Modal/ActionModal.tsx, src/components/Uploader/ProfileImageUploader.tsx, src/mocks/UtilApi.ts, src/pages/Profile/Modal/EditProfileModal.tsx, src/pages/Profile/Section/ProfileSection.tsx
- Close #676
- 프로필 수정 모달 UI 및 기능 구현하였습니다.
- 프로필 이미지 전용 이미지 업로더 추가로 생성하였습니다.
- (기존의 이미지 업로더에 확장하거나 활용하는 방법으로 하고 싶었는데 일단 빠른 구현이 우선적일 것 같아서 이미지 업로더 로직은 그대로 가져오고 UI만 변경하는 식으로 처리하였습니다. 추후 시간되면 리팩토링 해보겠습니다!)
- ActionModal 반응형 적용
- ActionModal 내용부에 최소 width가 적용되어 있어서 모바일 화면에서 스크롤이 적용되는 이슈가 있어서 모바일에서는 최소 width 적용 안 하고 화면에 맞게 처리할 수 있도록 해주었습니다.
- 기존 프로필 정보 받아와 띄워주고 수정할 수 있도록 처리하였습니다.
- (작업하면서 보이는 사소한 refactoring 이 PR과 직접적인 관련은 없지만 보인김에 몇몇개 바로 해주었습니다.)
- 예상 소요 시간 10분
- 학번은 기존 값 받아 오는 거 API 추가 요청해둔 상태라서 추가 이슈로 적용 예정입니다.
=> Feature/프로필 수정 모달 #676

src/api/memberApi.ts, src/components/Modal/ConfirmModal.tsx, src/pages/Profile/Modal/EditAccountModal.tsx, src/pages/Profile/Section/ProfileSection.tsx
- #679 
- 계정 정보 수정 모달 이메일 변경, 비밀번호 변경 기능 구현하였습니다.
- 이메일 변경, 비밀번호 변경 한 컴포넌트로 처리하기엔 너무 크고, 파일 분리하기에는 구조 너무 세분화하는 것 같기도하고 어떻게 잡아야할 지 모르겠어서 한 파일 내에서 컴포넌트 쪼개주었습니다. 가장 아래에 있는 컴포넌트가 메인 컴포넌트 입니다!
- 이메일 인증과 비밀번호 관련 유효성 검사 등 로직은 회원가입 부분과 거의 동일합니다!
- 15분
- 현재 이메일 변경은 정상적으로 동작 안 돼서 백엔드에 문의 넣어둔 상태이고, 인증 메일 발송 시 유효시간 받아오도록 API 수정 요청 드려놓은 상태입니다.
- 탈퇴하기 해당 PR 머지되면 추후 작업 예정입니다.
=> Feature/계정 정보 수정 모달 #679

src/pages/Study/Modal/StudyModal.tsx, src/pages/Study/Study.tsx
- #428
- 스터디 검색 필터 적용하였습니다.
- 검색된 기간에 스터디 목록이 없을 경우 빈 화면 -> 안내 문구 추가해주었습니다.
- 셀렉터를 통해 선택한 기간의 스터디 목록을 불러오도록 처리해주었습니다. (default로는 현재 년도와 학기 불러 오도록 했습니다.)
- 년도 목록에 2022년 이전과 2022년 ~ 현재년도로 구성될 수 있도록 처리해주었습니다.
- 스터디 추가/수정 시에도 검색 기간에 대한 추가/수정으로 반영되도록 해주었습니다.
- 예상 소요 시간 7분
=> Feature/스터디 검색 필터 적용 #428

src/components/Layout/Header/Header.tsx, src/components/Layout/MainLayout.tsx, src/components/Layout/Sidebar/Sidebar.tsx, src/constants/keeperTheme.ts
- Close #700
- 헤더 사이드바 반응형에 따른 처리 해주었습니다.
- 헤더에 사이드바 열고 닫을 수 있는 버튼 추가해주었습니다. 기본 웹뷰에서는 고정해두고, lg 사이즈 이하 부터 열고 닫을 수 있도록 해주었습니다.
- 7분
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/b9a80b31-2d63-4b7f-aea4-3345d587f9b0
=> Feature/헤더 사이드바 반응형 #700

src/api/memberApi.ts, src/hooks/useGetApiError.ts, src/pages/Profile/Modal/EditAccountModal.tsx
- Close #679 
- 탈퇴 기능 추가하였습니다.
- 탈퇴 기능 구현하고, 탈퇴 시 localstorage 멤버 정보 지워주고, 메인페이지로 이동하도록 처리하였습니다.
- 5분
- 현재 탈퇴 시 500에러 발생하는데 백엔드쪽에 문제 전달하였고, 수정 해주시기로 하였습니다!
=> Feature/계정 정보 수정 모달 - 탈퇴하기 #679

src/components/Layout/Container/FullContainer.tsx, src/components/Layout/Header/Header.tsx, src/components/Layout/MainLayout.tsx, src/pages/login/Login.tsx, src/pages/login/Search/SearchID.tsx, src/pages/login/Search/SearchPW.tsx, src/pages/login/Search/SearchPWFirstStep.tsx, src/pages/login/Search/SearchPWSecondStep.tsx, src/pages/login/Search/SearchPWThirdStep.tsx, src/pages/login/SearchAccount.tsx
- Close #705
- 로그인, 아이디/비밀번호 찾기 반응형 적용하였습니다.
- 10분
- 중첩된 태그 제거 등 일부 리팩토링도 같이 적용돼서 변경 사항이 크게 잡혔는데 `sm` 등 반응형 크기 적용한 부분 중점으로 봐주시면 될 것 같습니다!
|Before|After|
|------|-----|
|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/bb2966ec-c7e9-47cf-8f77-1f5f08958b3b)|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/9e8d39d4-8a23-47db-9e93-ce26856510be)|
|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/fd685cf9-c132-4dbe-8783-e776088c1999)|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/375c17a4-d517-4511-9a66-7c1253f53b54)|
|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/44380d1f-5e61-470d-8791-0cea5f200e4d)|![image](https://github.com/KEEPER31337/Homepage-Front-R2/assets/78 …
=> Feature/로그인 반응형 적용 #705

src/components/Input/AutoComplete.tsx, src/pages/Study/Modal/StudyModal.tsx, src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx, src/pages/admin/MeritManage/Modal/AddMeritModal.tsx
#713
AutoComplete z index 제거
- eslint 오류수정
- AutoComplete z index 제거, 페이지에서 안보이는 문제 해결
- 모달창에서 사용할 경우 모달창을 안넘어가려면 -10 적용
2분
=> refector : AutoComplete z index 제거

src/components/Table/StandardTable.interface.ts, src/components/Table/StandardTable.tsx
- Close #721
- #130 
- 테이블 셀 선택 가능하도록 확장하였습니다.
- 5분
- `Cell` 타입 바로 생각 안 나서 일단 `unknown`으로 했는데 혹시 타입 어떻게 지정하면 좋을 지 떠오르는 거 있으면 코멘트 부탁드립니다!
```tsx
...
const onCellClick = ({ cellData }: { cellData: Cell<ExampleRowType> }) => {
console.log(cellData);
};
return (
<StandardTable<ExampleRowType>
...
onCellClick={onCellClick}
...
/>
);
...
```
=> feat : 테이블 셀 선택 기능 확장

src/api/dto.ts, src/api/seminarApi.ts, src/pages/admin/SeminarManage/SeminarManage.tsx
- Close #723
- 세미나 관리 세미나 cell 클릭 시 상태 변경에 사용되는 출석 정보 다 받아오도록 처리해주었습니다.
- api 응답 변환 관련에서 코멘트 남겨 두겠습니다!
- ~선행 PR #722 먼저 리뷰 부탁드립니다!~ 머지 완료
- 현재 기수랑 이름도 셀 클릭이 되는데 해당 부분은 추후 클릭 안 되도록 처리 예정입니다!
=> Feature/세미나 관리 세미나 cell 클릭 시 해당 출석 정보 다 받아오도록 처리 #723

src/pages/rank/Rank.tsx
#685
랭킹페이지 반응형 처리
- lg 이하일시 세로정렬
- lg 이하일시 TapCatd 목록 높이 조절
2분
기존에 어느정도 반응형이 되어 있어 큰 작업은 없습니다.
기존에 있던 반응형 적절한지 확인 부탁드립니다.
=> design : 랭킹페이지 반응형 처리

src/api/dto.ts, src/api/memberApi.ts, src/pages/admin/ActiveMemberManage/ActiveMemberManage.tsx, src/pages/admin/ActiveMemberManage/Button/ChangeMemberTypeButton.tsx, src/pages/admin/ActiveMemberManage/Card/MemberCard.tsx, src/pages/admin/ActiveMemberManage/Input/ChangeMemberTypeInput.tsx, src/pages/admin/ActiveMemberManage/MemberCard.tsx, src/pages/admin/ActiveMemberManage/Section/MemberTypeSection.tsx, src/pages/admin/ActiveMemberManage/Selector/SortSelector.tsx, src/router/useMainRouter.tsx
- #702
- 활동인원관리 페이지 구현했습니다
- 정렬 기능
- 인원 선택 (회원 카드 누를때 + 오토컴플리트에서 클릭할때 같이 적용되도록)
- 타입 변경 기능
-
- 타입변경 버튼누를때, "총 n명을 삭제하시겠습니까? 와 사람 리스트 띄워주는건 추후에.. 하겠습니다..
- 15분
- 파일나눌때 중복되는 props가 많아서 이걸 파일 여러개로 분리하는게 의미있을까하는데,, 더 좋은 방법 있으시면 말씀부탁드립니다.!
=> Feature/활동인원 관리 페이지 구현 #702

src/components/Tab/StandardTab.tsx, src/pages/Profile/Profile.tsx, src/router/useMainRouter.tsx
- Close #748
- 프로필 탭별로 url 적용했습니다!
- 7분
- 원래 hash로 처리하려고 했는데 기존에 적용되어 있는 searchParam과 탭과 url간 연동 등 처리하는 게 까다로워서 그냥 경로로 처리해주었습니다..! 혹시 다른 좋은 방법 있다면 제안해주세요!
- 새로고침 시 탭 패널 그대로인데 탭에 활성화된 탭 색은 default 값으로 돌아가서 해당 관련 처리 추가로 해줘야 할 것 같습니다!
=> feat : 프로필 탭별 url 적용

src/api/SearchAccountApi.ts, src/pages/login/Search/SearchPWFirstStep.tsx, src/pages/login/Search/SearchPWSecondStep.tsx
- Close #627
- Close #761
- Close #762
- Close #774
- 비밀번호 찾기 인증 코드 관련 처리와 비밀번호 찾기 관련 에러 처리 작업해주었습니다.
- 인증 코드 확인 api가 인증 버튼 클릭 후 확인해야 하는데 페이지 접근 시 바로 호출돼서 에러 발생하던 거 fix 해주었습니다.
- 비밀번호 찾기 인증코드 전송 시, 아이디와 이메일이 필요한데 아이디 입력하지 않은 지 아무런 안내 없이 인증이 안 되는 이슈가 있어서 이메일 인증코드 전송 시 아이디, 이메일 입력 필수 처리하고 입력값 없을 시 에러 문구 띄워주도록 처리하였습니다.
- 비밀번호 찾기 이메일 형식 안 맞을 때 버튼은 비활성화인데 안내문구가 없어서 blur 시 형식 맞추라는 에러 문구 표시해주었습니다.
- 인증 요청 전에는 `인증 메일 재전송`이나 `다른 이메일로 변경` 기능이 필요 없기 때문에 인증 요청 후에만 인증 메일 안내 문구 뜨도록 처리하였습니다.
- 인증 코드 타이머 설정을 컴포넌트 props로 바로 전달했어서 리렌더링 될 때마다 타이머 초기화되는 버그 fix 해주었습니다.
- 비밀번호 각 단계에서 에러 발생 후 수정이 안되는 문제 fix나 이벤트에 따른 문구 관련 처리 해주었습니다.
- 예상 소요 시간 15분
=> Feature/비밀번호 찾기 인증 코드 관련 처리

src/api/dto.ts, src/api/meritApi.ts, src/pages/admin/MeritManage/MeritManage.tsx, src/pages/admin/MeritManage/Modal/DeleteMeritLogModal.tsx, src/pages/admin/MeritManage/Modal/MemberMeritModal.tsx, src/pages/admin/MeritManage/Modal/SettingMeritTypeModal.tsx, src/pages/admin/MeritManage/Tab/MeritLogTab.tsx, src/pages/admin/MeritManage/Tab/MeritTypeTab.tsx, src/pages/admin/MeritManage/Tab/UserMeritTab.tsx
#686 
상벌점 페이지 api 변경사항 적용
- isMerit로 상점 벌점 구분합니다
- 상점 벌점 음수가 추가됩니다 ( 상쇄용 )
- 반응형 처리 적용했습니다 (표 가로 스크롤)
- api가 없는 Selector 제거했습니다
10분
반응형 표 가로 스크롤로 적용하여 글씨가 새로로 길어지는 현상을 없게 했는데 괜찮을까요?
추가로 O기 OOO의 상벌점내역 글씨가 모바일에서는 넘어가기는 하는데 큰 문제 없어보여 별다른 처리는 안했습니다. 필요하면 처리하겠습니다.
API에 없는 정렬과 필터를 제외하여 개수가 많이 줄었습니다.
=> Feature/상벌점페이지 정렬 필터링 #686

src/components/Table/StandardTable.interface.ts, src/components/Table/StandardTable.tsx, src/pages/admin/SeminarManage/SeminarManage.tsx
- #307, #786
- 테이블 column 좌측에 고정  가능하도록 처리하고 세미나 관리 테이블에 적용했습니다. (+고정된 column cell은 클릭 불가하도록 처리했습니다.)
- 10분
- 세미나 관리 테이블에 우측에 총 (출석, 지각, 결석, 개인사정) column도 고정해야하는데 API 나오면 우측 고정 기능도 추가 예정입니다!
https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/af9e8379-921d-4bd2-9d7b-9b528c47f98a
=> Feature/세미나 관리 테이블 관련 처리 #786

src/api/seminarApi.ts, src/pages/senimarAttend/SenimarAttend.tsx
- #792
- 배열 map 돌릴 때 key 중복값있어서 오류 발생하는 거 해결했습니다.
- 두 api에서 받아온 데이터를 한 배열로 다루는데, 두 데이터를 다 받아왔을 때 배열 set해주도록 변경했습니다.
- 동일한 queryKey로 서로 다른 세미나인데도 같은 캐싱된 값이 뜨는 버그 해결했습니다.
- 예상 소요 시간 10분
- 현재 db 변경사항 대기중이라 나머지 버그는 db 변경 후 처리 예정입니다!
=> Feature/세미나 출석 페이지 버그 픽스 #792

src/api/postApi.ts, src/components/Modal/ActionModal.tsx, src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Modal/SecretPostModal.tsx, src/pages/board/BoardView/Section/PostSection.tsx
- #789
-  작성자는 비밀번호 입력 안하고 확인 버튼만 눌러도 비밀글 조회 가능해야 하는데, 비밀번호 필수값 처리로 버튼 비활성화 처리해뒀어서 확인 버튼만으로 조회 불가능한 버그가 있어서 별도의 비활성화 넣지 않도록 처리했습니다.
-  api의 `isRead`로 주의 모달이 뜰 지 여부를 제어하는데 시험 게시판 첨부파일 바로 닫았다 열때 api가 동기화 되지 않은 상태가서 한 번 조회한 이후에도 모달이 뜨는 버그가 있어서 한 번 조회시 isRead값 캐싱데이터에서 변경해주어 처리해주었습니다.
-  비밀글 비밀번호 기입 엔터 가능하도록 처리했습니다.
-  비밀글 나간 후 password reset되도록 하여 다른 게시글로 갔다가 다시 접속 시 비밀글의 캐싱데이터로 비밀번호 입력 전에 게시글이 보이게 되는 버그 픽스했습니다.
- 10분
=> Feature/게시글 조회 페이지 버그 픽스 #789

src/api/dto.ts, src/components/Avatar/ServerAvatar.tsx, src/components/Card/PostingCard.tsx, src/constants/muiTheme.ts, src/pages/Profile/Section/FollowList.tsx, src/pages/Profile/Section/ProfileSection.tsx, src/pages/admin/ActiveMemberManage/Card/MemberCard.tsx, src/pages/board/BoardView/Card/CommentCardFooter.tsx, src/pages/board/BoardView/Card/CommentCardHeader.tsx, src/pages/board/BoardView/Section/BannerSection.tsx, src/pages/home/Trendings.tsx, src/pages/rank/Rank.tsx, src/pages/rank/TopCard.tsx
- Close #800
- 서버 프로필 받아오는 Avatar 공통 컴포넌트로 만들어주었습니다.
- Avatar mui 기본 테마 커스텀 했습니다.
- `ServerAvatar` 컴포넌트 만들었습니다.
- 기본에 Mui Avatar 컴포넌트 사용하던 부분 중 서버 프로필 받아오는 부분 공통 컴포넌트 사용으로 변경해주었습니다.
- 게시글 댓글 작성에 본인 프로필 받아오는 거 추가로 처리해주었습니다.
- 랭킹 페이지 썸네일 주소 연결 안 되어 있던 부분 연결해주었습니다.
- 랭킹 쪽에는 현재 api 변경 사항으로 일부분 썸네일 안 뜰 수 있습니다.
- 랭킹 api에서 썸네일 주소 안 보내주고 있는 부분은 요청해놨고, api만 작성되면 뜨도록 미리 dto 추가해서 짜놓았습니다. @jasper200207 나중에 api 변경되었다고 하면 제대로 뜨는 지 확인만 해보시면 될 것 같습니다!
- 랭킹 중 게임 랭킹과 포인트 랭킹 썸네일 받아오는 응답 필드 네이밍이 달라서 게임 랭킹 api 응답 필드 변경 요청 해두었습니다. @jasper200207 여기도 마찬가지로 dto 파일 미리 수정해놔서 변경되면 확인만 부탁드립니다!
=> Feature/avartar 서버 프로필 공통 컴포넌트 #800

src/api/seminarApi.ts, src/pages/admin/SeminarManage/Modal/EditSeminarAttendanceModal.tsx
- Close #808
- 리액트 쿼리 키에 page부분이 없어서, page를 이동함에도 api가 다시 안불러와지는 문제였음
- 이에 키에 page 추가. 또한 출석상태변경 api 에서도 똑같이 page를 추가해줌,
- 1분
=> fix : 세미나 관리 페이지 이동안되는 버그 해결

src/pages/Study/Modal/StudyModal.tsx
- Close #806 
- 스터디 링크 한 개도 입력 안 한 상태에서 추가 버튼 클릯시 1개 이상 링크 필수 문구 하이라이트 처리해주었습니다.
- 스터디 링크 etc에서 https:// 로 시작해야 한다는 에러문구는 제공하는데 바로 스터디 추가가 되는 버그가 있었는데 인풋 필드 invalid 시에 추가 안 되도록 처리해주었습니다.
- 기타 링크를 사용하려면 링크명과 링크 둘 다 입력해야 하도록 처리해주었습니다.
- 예상 소요 시간 3분
=> Feature/스터디 버그 픽스 #806

src/mocks/DutyManageApi.ts, src/pages/admin/DutyManage/Button/DutyProfileButton.tsx, src/pages/admin/DutyManage/DutyManage.tsx, src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx, src/pages/admin/DutyManage/Tooltip/DutyProfileTooltip.tsx
- #798 
- 직책 변경시 다른 직책이 변경되는 오류 수정
- 사람 선택하지 않고 직책 변경 시 해당 직책 제거
- 직책에 관련된 업무 설명 글 수정
- 직책 변경시 업무 설명 글이 떠서 변경하기 힘든 이슈 해결
- `5분`
=> fix : 직책관리 페이지 버그 픽스

src/pages/admin/ActiveMemberManage/Button/MemberTypeChangeButton.tsx, src/pages/admin/ActiveMemberManage/Input/MemberTypeChangeInput.tsx, src/pages/admin/ActiveMemberManage/memberTypes.ts
- Close #816
- 버튼 크기 통일 
- 버튼 크기 모바일에서 키움
- 오토컴플리트 기수별 그룹화 추가
- 비회원 컬러 추가
- 5분
=> fix : 기수별 그룹화 및 비회원 색깔 추가

src/pages/senimarAttend/SenimarAttend.tsx
- Close #821
- 이전, 다음 글자 -> 아이콘으로 변경
- 모바일에선 중간 카드를 맨처음에 보여주도록
=> fix : 모바일에선 중간 카드를 맨처음에 보여주도록

src/api/dto.ts, src/api/libraryApi.ts, src/pages/Library/Library.tsx, src/pages/Profile/Tab/BookTab/BookTab.tsx
- Close #866 
- 쿼리키 포맷 수정
- PageAndSize 타입을 원래는 하드코딩으로 page,size 각각 적어줬는데 extend로 가져옴
- `useGetBookBorrowsQuery` -> `useGetBorrowedBookListQuery`로 네이밍 변경
- 3분. 잘 돌아가는거 확인했습니다!
=> Feature/library api 쿼리키 포맷 통일 #866

src/api/signUpApi.ts, src/pages/Profile/Modal/EditAccountModal.tsx, src/pages/SignUp/Section/SignUpFirstInputSection.tsx, src/pages/SignUp/Section/SignUpSecondInputSection.tsx
- Close #863
- sign up api 쿼리키 포맷 통일해주었습니다.
**(✅는 변경 후 정상동작 확인한 사항입니다!)**
- 포맷 통일
- ✅ 로그인 중복 확인(`useCheckLoginIdDuplicationQuery`)
- ✅ 이메일 중복 확인(`useCheckEmailDuplicationQuery`)
- ✅ 학번 중복 확인(`useCheckStudentIdDuplicationQuery`)
- 오타 수정
- ✅ 회원가입 시 비밀번호 확인란 일치 여부  검증
- ✅ 계정 변경 시 새 비밀번호 확인란 일치 여부  검증
- 리팩토링하다가 개선 필요해보이는 부분 `REVIEW` 앵커로 주석 달아두었습니다. 언제 한 번 리팩토링 주제로 `REVIEW`, `TODO` 앵커 해결하기 넣어두어도 좋을 것  같아요!
- params 변수 빼는 방식 이렇게 하면 될 지 확인 부탁드려요!
=> Feature/sign up api 쿼리키 포맷 통일 #863

src/api/libraryManageApi.ts
- Close #866 
Library Manage Api 쿼리키 포멧 통일
- borrowInfoList, overdueInfoList의 경우 같은 api 주소지만, request랑 response가 다른부분이 많아서 별도의 key로 만들어 줬습니다!
3분
=> refactor :  query key 수정

src/api/meritApi.ts, src/api/pointApi.ts
- Close #865 
Merit Api 쿼리키 포멧 통일
querykey factory에 맞춰 수정하였습니다.
1분
=> refactor : merit Api querykey factor

src/api/authApi.ts
- close #881 
- 로그아웃시 api 결과와 무관하게 localstorage 비우기
- 리뷰 예상 시간 : 1분
=> fix : 로그아웃 에러 처리

src/constants/helperText.ts, src/pages/Study/Modal/StudyModal.tsx
- close #879 
- 로그인 안했을때 토스트 메시지 띄워주도록 수정.
- 0.5분
=> refactor: 로그인 안했을 때 토스트 메시지 띄워주도록

src/components/NeedAuth/NeedAuth.tsx, src/components/NeedAuth/NeedLogin.tsx, src/hooks/useCheckAuth.ts, src/router/useMainRouter.tsx
- close #888 
어드민페이지 등 권한이 없어도 페이지에 접속되는 문제 해결
- NeedLogin, NeedAuth 컴포넌트를 통해 페이지가 렌더링 되기 전 localstorage의 권한을 확인하도록 설정
- 기존에도 api에서 막고 있었기에 프론트에서 경고 띄우기 및 한번 더 거르는 역할
- 리뷰 예상 시간 : 10분
=> Feature/어드민페이지 url로 접근가능 #888

src/api/postApi.ts, src/components/Editor/StandardEditor.tsx, src/constants/apiResponseMessage.ts
- Close #454 
- Toast UI 에디터에 이미지 업로드 시 서버에 이미지 저장 후 url 받아와 해당 url의 이미지 띄워주도록 처리
- Toast UI 에디터에서 기본적으로 제공하는 이미지 업로드 로직은 파일이 base64로 인코딩되어 삽입되는 형태여서 글자수가 길어져 게시글 전체 글자수 제한에 걸리게 되는 이슈가 있었습니다.
- 서버에 이미지 업로드하여 해당 url로 처리하는 방식으로 변경하여 해당 이슈 해결하였습니다.
- 로딩 처리 및 이미리 업로드 중 텍스트 입력 가능하도록 처리하기 위해 Toast UI Editor에서 기본적으로 제공하는 `addImageBlobHook`의 `callback` 파라미터 사용하는 대신 선택 범위에 텍스트 넣어주는 방식으로 처리하였습니다.
- 파일 사이즈 제한 초과 및 업로드 실패 시 에러 토스트 메시지 띄워주도록 처리하였습니다.
| BEFORE | AFTER |
|--------| --------|
|<img width="534" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/ad6301fd-3a4a-4c04-a7b3-d3ef7a505e40"> | <img width="534" alt="image" src="https://github.com/KEEPER31337/Homepage-Front-R2/assets/78250089/616cc795-a4b0-4278-891f-a0d6e34298fd">|
- 궁금한 부분 편하게 질문 주셔도 됩니다~!
> [!NOTE]
> …
=> Feature/toast UI 이미지 핸들러 #454

src/api/postApi.ts, src/pages/board/BoardView/BoardView.tsx, src/pages/board/BoardView/Section/BannerSection.tsx, src/pages/board/BoardView/Section/PostSection.tsx, src/pages/board/BoardWrite/BoardWrite.tsx
> close #880 
> 1번, 2번, 2-1번 해결완료
> 1. 게시글 수정 페이지에서 글을 수정해도 수정하기 버튼이 활성화되지 않습니다.
- **해결방법** : onBlur() 함수에서 onChange() 함수로 변경해서 input값 변경시에 수정버튼 활성화 되도록 수정했습니다. 
<br/>
> 2. 게시글 수정 페이지에서 새로고침을 하면 첨부파일이 보이지 않습니다. 이후 해당 게시판에서 글 수정 버튼을 눌러도 똑같이 보이지 않습니다.
- **해결방법** : `getQueryData` 로 데이터를 로드하던 방식을 `useGetPostFilesQuery` 함수를 사용하여 데이터를 받아오는 방식으로 수정하였습니다. 
- => `getQueryData` 함수를 사용하면 새로 고침시, 캐싱된 데이터가 날라가기때문에 기존에 저장되어있는 값을 가져오지 못하는 문제가 발생합니다.
- `useGetPostFilesQuery` 함수를 사용하여 새로 고침하더라도 페이지에서 API 함수를 호출해서 데이터를 가져오는 방식으로 변경하여 해결하였습니다. 
<br/>
> 2-1. 새로고침을 해서 첨부파일이 보이지 않게 되었을 때 첨부파일 목록을 열어야 수정할 때 첨부파일이 보입니다.
- **해결방법** : `BoardView` 페이지 로딩시 `fileOpen` 변수의 초기값이 **false**로 설정되어 있어 첨부파일 목록을 펼치지 않으면 파일 데이터를 받아오지 않아 수정버튼을 눌러도 데이터가 전달되지 않았습니다.
- `fileOpen`의 변수 초기값을 **true**로 설정하고 `useEffect()` 함수를 사용하여 페이지 …
=> Feature/게시글 수정하기 버튼 활성화 안 됨 #880

.eslintrc.js, src/components/Uploader/FileUploader.tsx, src/constants/apiResponseMessage.ts
- #479
- #459 
- 업로드 시 드랍되는 파일의 크기, 확장자를 확인한다.
- 형식과 맞지 않는 파일일 시 관련 toast 메시지를 띄운다.
- 파일의 크기(30MB)의 경우 `MAX_FILE_SIZE` 상수를 사용하였습니다.
- `onDropRejected` 속성을 활용하여 조건에 대해 유효하지 않은 파일을 다룬다.
- 리뷰 예상 시간 : 5분
https://github.com/KEEPER31337/Homepage-Front-R2/assets/127263392/b4979fb7-3e1e-4f49-b900-120b2ce85711
=> Feature/파일 업로더 세부 기능 구현 #479

src/pages/admin/ActiveMemberManage/Input/MemberTypeChangeInput.tsx, src/pages/admin/DutyManage/Modal/ChangeRolePersonModal.tsx
- #892
- '활동 회원 관리 페이지'와 '직책 관리 페이지'의 회원 검색창에 뜨는 회원 목록에서, 기수별 순서가 제대로 정렬되지 않고 1, 10, 11, 12 ... 3, 4, 5 순으로 보이는 문제가 발생하여 로직을 다시 구현.
- group(기수) 값을 float로 변환하여 sort 메서드를 활용해 오름차순으로 정렬하였습니다.
- 기수가 동일할 경우 localeCompare 메서드를 활용해 알파벳순으로 정렬하였습니다.
> 리뷰 예상 시간 : 1분
=> Feature/검색창 기수별 정렬순서 수정 #892
